const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const API=(window.B4_API_URL||'').replace(/\/$/,'');
const S={lang:localStorage.b4Lang||'en',theme:localStorage.b4Theme||'light',view:'dashboard',me:null,linked:[],students:[],teachers:[],subjects:[],schedule:[],assignments:[],resources:[],exams:[],announcements:[],messages:[],attendance:[],developers:[],badges:[],accounts:[],permissions:[],users:[],teacherMessages:[],notifications:[],examReview:null,error:''};
const L={en:{dashboard:'Dashboard',students:'Students',teachers:'Teachers',subjects:'Subjects',schedule:'Schedule',assignments:'Assignments',resources:'Resources',exams:'Exam Center',announcements:'Announcements',chat:'Class Chat',teacherChat:'Teacher Chat',attendance:'Attendance',admin:'Admin Center',teacherCenter:'Teacher Center',settings:'Settings',developers:'Developers',login:'Login',logout:'Log out',activate:'Activation Key',ai:'B4 AI',search:'Search everything...',guest:'Guest',save:'Save',add:'Add',edit:'Edit',delete:'Delete',open:'Open resource',light:'Light mode',dark:'Dark mode'},ar:{dashboard:'الرئيسية',students:'الطلاب',teachers:'المدرسين',subjects:'المواد',schedule:'الجدول',assignments:'الواجبات',resources:'المصادر',exams:'الامتحانات',announcements:'الإعلانات',chat:'شات الفصل',teacherChat:'شات المدرسين',attendance:'الحضور',admin:'مركز الإدارة',teacherCenter:'مركز المدرس',settings:'الإعدادات',developers:'المطورون',login:'تسجيل الدخول',logout:'تسجيل الخروج',activate:'مفتاح التفعيل',ai:'مساعد B4',search:'ابحث...',guest:'زائر',save:'حفظ',add:'إضافة',edit:'تعديل',delete:'حذف',open:'فتح المصدر',light:'الوضع النهاري',dark:'الوضع الليلي'}};
const t=k=>L[S.lang][k]||k;
const PERMS=[['MANAGE_CHAT','Manage Chat'],['MANAGE_ACCOUNTS','Manage Accounts'],['MANAGE_PERMISSIONS','Manage Permissions'],['VIEW_LOGS','View Logs'],['VIEW_ADMIN_CENTER','View Admin Center'],['MANAGE_STUDENTS','Manage Students'],['MANAGE_TEACHERS','Manage Teachers'],['MANAGE_ROLES','Manage Roles'],['MANAGE_ADMINS','Manage Admins'],['MANAGE_BADGES','Manage badges'],['MANAGE_SUBJECTS','Manage subjects'],['MANAGE_SCHEDULE','Manage schedule'],['MANAGE_ASSIGNMENTS','Manage assignments'],['MANAGE_RESOURCES','Manage resources'],['MANAGE_EXAMS','Manage exams'],['MANAGE_ANNOUNCEMENTS','Manage announcements'],['MANAGE_ATTENDANCE','Manage attendance'],['MANAGE_CHAT','Manage class chat'],['MANAGE_TEACHER_CHAT','Teacher chat'],['VIEW_LOGS','View logs'],['MANAGE_ANALYTICS','Attendance analytics'],['USE_AI','Use AI'],['MANAGE_DEVELOPERS','Manage developers'],['ADMINISTRATOR','Administrator']];
const api=async(path,opt={})=>{const r=await fetch(API+path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Request failed');return d};
const toast=m=>{const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2500)};
const close=()=>{$('#back')?.classList.remove('show')};window.b4Close=close;
const modal=h=>{$('#modal').innerHTML='<div class="modal">'+h+'</div>';$('#back').classList.add('show')};
const can=p=>{if(!S.me)return false;if(Number(S.me.is_super_admin)===1||S.me.role==='SUPER_ADMIN')return true;return (S.me.permissions||[]).includes(p)};
const nav=[['dashboard','⌂'],['students','♙'],['teachers','♟'],['subjects','▣'],['schedule','◫'],['assignments','✓'],['resources','▤'],['exams','⌁'],['announcements','◈'],['chat','◌'],['attendance','◉']];
function go(v){if(!S.me&&!['students','teachers','subjects','schedule'].includes(v)){loginModal();return}S.view=v;render();window.scrollTo({top:0,behavior:'smooth'});$('#side')?.classList.remove('open')}
function buildNav(){if(!S.me)return nav.filter(x=>['students','teachers','subjects','schedule'].includes(x[0])).map(x=>'<button data-v="'+x[0]+'" class="'+(S.view===x[0]?'active':'')+'">'+x[1]+' <span>'+t(x[0])+'</span></button>').join('');
let a=nav.map(x=>'<button data-v="'+x[0]+'" class="'+(S.view===x[0]?'active':'')+'">'+x[1]+' <span>'+t(x[0])+'</span></button>').join('');
if(S.me.role==='TEACHER'||can('MANAGE_ASSIGNMENTS'))a+='<button data-v="teacherCenter" class="'+(S.view==='teacherCenter'?'active':'')+'">◈ <span>'+t('teacherCenter')+'</span></button>';
if(can('MANAGE_TEACHER_CHAT')||S.me.role==='TEACHER'||S.me.role==='SUPER_ADMIN')a+='<button data-v="teacherChat" class="'+(S.view==='teacherChat'?'active':'')+'">☷ <span>'+t('teacherChat')+'</span></button>';
if(can('VIEW_ADMIN_CENTER'))a+='<button data-v="admin" class="'+(S.view==='admin'?'active':'')+'">⚙ <span>'+t('admin')+'</span></button>';
a+='<button data-v="settings" class="'+(S.view==='settings'?'active':'')+'">⚙ <span>'+t('settings')+'</span></button>';if(Number(S.me.is_super_admin)===1||S.me.role==='SUPER_ADMIN')a+='<button data-v="developers" class="'+(S.view==='developers'?'active':'')+'">⌘ <span>'+t('developers')+'</span></button>';return a}
function title(h,p,b=''){return '<div class="title"><div><div class="eyebrow">B4 • TELECOMMUNICATION</div><h1>'+h+'</h1><p>'+p+'</p></div><div class="actions">'+b+'</div></div>'}
function dashboard(){return title('Welcome to B4 👋','Your class, academics and communication in one place.',S.me?'<button class="btn primary" onclick="aiModal()">✦ '+t('ai')+'</button>':'<button class="btn primary" onclick="loginModal()">'+t('login')+'</button>')+
'<div class="hero"><div><span class="eyebrow">WE SCHOOL • B4</span><h1>B4 Telecommunication</h1><p>Official class portal for students and teachers.</p><button class="btn" onclick="aiModal()">✦ Ask B4 AI</button></div></div>'+
'<div class="grid stats"><div class="card stat"><small>Students</small><b>'+S.students.length+'</b></div><div class="card stat"><small>Teachers</small><b>'+S.teachers.length+'</b></div><div class="card stat"><small>Subjects</small><b>'+S.subjects.length+'</b></div><div class="card stat"><small>Assignments</small><b>'+S.assignments.length+'</b></div></div>'+
'<div class="grid c2"><div class="card"><div class="head"><h3>'+t('announcements')+'</h3>'+ (S.me?'<button class="btn ghost" onclick="go(\'announcements\')">View</button>':'')+'</div>'+(!S.me?'<p class="muted">Log in as a B4 student or teacher to see class announcements.</p>':S.announcements.slice(0,5).map(a=>'<div class="item"><div class="grow"><b>'+esc(a.title)+'</b><p class="muted">'+esc(a.body||'')+'</p></div></div>').join('')||'<div class="empty">No announcements.</div>')+'</div>'+
'<div class="card"><div class="head"><h3>✦ '+t('ai')+'</h3><span class="badge">ONLINE</span></div><p class="muted">AI is visible to everyone, but only B4 accounts can use it.</p><button class="btn primary" onclick="aiModal()">Open AI</button></div></div>'}
function peopleCard(x,type){return '<article class="card"><div class="item" style="padding:0;border:0"><img class="avatar" src="'+esc(x.avatar_url||'assets/logo.svg')+'"><div class="grow"><b>'+esc(x.display_name||x.official_name||'')+'</b><small class="muted">'+esc(type==='student'?x.student_code||'':x.teacher_code||'')+'</small></div><span class="badge">'+type+'</span></div>'+(can(type==='student'?'MANAGE_STUDENTS':'MANAGE_TEACHERS')?'<div class="actions-row"><button class="btn ghost" onclick="'+(type==='student'?'studentEdit('+x.id+')':'teacherEdit('+x.id+')')+'">Edit</button><button class="btn danger" onclick="'+(type==='student'?'studentDelete('+x.id+')':'teacherDelete('+x.id+')')+'">Delete</button></div>':'')+'</article>'}
function studentsV(){return title(t('students'),'B4 student directory.',can('MANAGE_STUDENTS')?'<button class="btn primary" onclick="studentEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c3">'+S.students.map(x=>peopleCard(x,'student')).join('')+'</div>'}
function teachersV(){return title(t('teachers'),'B4 teacher directory.',can('MANAGE_TEACHERS')?'<button class="btn primary" onclick="teacherEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c3">'+S.teachers.map(x=>peopleCard(x,'teacher')).join('')+'</div>'}
function subjectsV(){return title(t('subjects'),'Subjects and resources. '+(can('MANAGE_SUBJECTS')?'You can manage them from here.':''),can('MANAGE_SUBJECTS')?'<button class="btn primary" onclick="subjectEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c3">'+S.subjects.map(s=>'<article class="card"><div class="head"><h3>'+esc(s.name)+'</h3><span class="badge">'+(s.progress||0)+'%</span></div><p class="muted">'+esc(s.teacher_name||'')+'</p><div class="barline"><span style="width:'+(s.progress||0)+'%"></span></div><button class="btn ghost" onclick="go(\'resources\')">'+t('open')+' →</button>'+(can('MANAGE_SUBJECTS')?'<div class="actions-row"><button class="btn ghost" onclick="subjectEdit('+s.id+')">Edit</button><button class="btn danger" onclick="subjectDelete('+s.id+')">Delete</button></div>':'')+'</article>').join('')||'<div class="card empty">No subjects.</div>'+'</div>'}
function scheduleV(){return title(t('schedule'),'Official B4 schedule.',can('MANAGE_SCHEDULE')?'<button class="btn primary" onclick="scheduleEdit()">Edit schedule</button>':'')+'<div class="card tablewrap"><table class="table"><thead><tr><th>DAY</th><th>P1</th><th>P2</th><th>P3</th><th>P4</th></tr></thead><tbody>'+S.schedule.map(r=>'<tr><td><b>'+esc(r.day_name)+'</b></td><td>'+esc(r.p1||'—')+'</td><td>'+esc(r.p2||'—')+'</td><td>'+esc(r.p3||'—')+'</td><td>'+esc(r.p4||'—')+'</td></tr>').join('')+'</tbody></table></div>'}
function tasksV(){return title(t('assignments'),'Assignments and deadlines.',can('MANAGE_ASSIGNMENTS')?'<button class="btn primary" onclick="assignmentEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c2">'+S.assignments.map(a=>'<article class="card"><div class="head"><h3>'+esc(a.title)+'</h3><span class="badge">'+esc(a.status||'OPEN')+'</span></div><p class="muted">'+esc(a.subject_name||'')+'</p><p>'+esc(a.description||'')+'</p><div class="meter"><span>Deadline</span><b>'+esc(a.due_at||'—')+'</b></div>'+(can('MANAGE_ASSIGNMENTS')?'<div class="actions-row"><button class="btn ghost" onclick="assignmentEdit('+a.id+')">Edit</button><button class="btn danger" onclick="delAPI(\'/api/admin/assignments/'+a.id+'\',\'Assignment deleted\')">Delete</button></div>':'')+'</article>').join('')||'<div class="card empty">No assignments.</div>'+'</div>'}
function resourcesV(){return title(t('resources'),'Lessons, links and PDFs.',can('MANAGE_RESOURCES')?'<button class="btn primary" onclick="resourceEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c3">'+S.resources.map(r=>'<article class="card"><span class="badge">'+esc(r.resource_type||'RESOURCE')+'</span><h3>'+esc(r.title)+'</h3><p class="muted">'+esc(r.description||'')+'</p>'+(r.url||r.file_url?'<a class="btn primary" href="'+esc(r.url||r.file_url)+'" target="_blank" rel="noopener">'+t('open')+' →</a>':'')+(can('MANAGE_RESOURCES')?'<div class="actions-row"><button class="btn ghost" onclick="resourceEdit('+r.id+')">Edit</button><button class="btn danger" onclick="delAPI(\'/api/admin/resources/'+r.id+'\',\'Resource deleted\')">Delete</button></div>':'')+'</article>').join('')||'<div class="card empty">No resources.</div>'+'</div>'}
function examsV(){return title(t('exams'),'Exams, submissions and results.',can('MANAGE_EXAMS')?'<button class="btn primary" onclick="examEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid c2">'+S.exams.map(e=>'<article class="card"><div class="head"><span class="badge">'+esc(e.status)+'</span><span class="muted">'+esc(e.subject_name||'')+'</span></div><h3>'+esc(e.title)+'</h3><p class="muted">'+esc(e.description||'')+'</p><div class="meter"><span>Starts</span><b>'+esc(e.starts_at||'Now')+'</b></div><div class="actions-row"><button class="btn primary" onclick="startExam('+e.id+')">Open</button>'+(can('MANAGE_EXAMS')?'<button class="btn ghost" onclick="examEdit('+e.id+')">Edit</button><button class="btn danger" onclick="delAPI(\'/api/admin/exams/'+e.id+'\',\'Exam deleted\')">Delete</button><button class="btn ghost" onclick="submissions('+e.id+')">Submissions</button>':'')+'</div></article>').join('')||'<div class="card empty">No exams.</div>'+'</div>'}
function announcementsV(){return title(t('announcements'),'Official class announcements.',can('MANAGE_ANNOUNCEMENTS')?'<button class="btn primary" onclick="announcementEdit()">＋ '+t('add')+'</button>':'')+'<div class="grid">'+S.announcements.map(a=>'<article class="card"><div class="head"><span class="badge">'+esc(a.category||'General')+'</span><small>'+esc(a.created_at||'')+'</small></div><h3>'+esc(a.title)+'</h3><p>'+esc(a.body||'')+'</p>'+(can('MANAGE_ANNOUNCEMENTS')?'<div class="actions-row"><button class="btn ghost" onclick="announcementEdit('+a.id+')">Edit</button><button class="btn danger" onclick="delAPI(\'/api/admin/announcements/'+a.id+'\',\'Announcement deleted\')">Delete</button></div>':'')+'</article>').join('')+'</div>'}
function chatV(){return title(t('chat'),'Live class chat.')+'<div class="card chat"><div class="messages" id="messages">'+S.messages.map(messageHTML).join('')+'</div><div id="typing" class="typing-indicator"></div><form class="chatform" onsubmit="sendChat(event)"><input id="chatInput" oninput="typing(!!this.value.trim())" placeholder="Write a message..."><button class="btn primary">➤</button></form></div>'}
function messageHTML(m){
  const reply=m.reply_to_id?'<div class="reply-preview"><b>↩ '+esc(m.reply_display_name||'Reply')+'</b><span>'+esc(m.reply_body||'')+'</span></div>':'';
  const edited=m.edited_at?'<small class="edited">edited</small>':'';
  return '<div class="msg '+(S.me&&Number(m.user_id)===Number(S.me.id)?'me':'')+'" onclick="messageMenu(event,'+m.id+')"><img class="avatar" src="'+esc(m.avatar_url||'assets/logo.svg')+'"><div><b>'+esc(m.display_name||'Deleted user')+'</b>'+reply+'<div class="bubble">'+esc(m.body||'')+edited+'</div><small class="muted">'+esc(m.created_at||'')+'</small></div></div>'
}
function attendanceV(){if(!can('MANAGE_ATTENDANCE'))return title(t('attendance'),'Your attendance record.')+'<div class="card"><p>Attendance management is available to authorized staff.</p></div>';return title(t('attendance'),'Mark attendance and view analysis.','<button class="btn primary" onclick="attendanceLoad()">Refresh</button>')+'<div id="attendanceRoot"></div>'}
function adminV(){const cards=[['roles','Roles','MANAGE_ROLES'],['permissions','Permissions','MANAGE_PERMISSIONS'],['accounts','Accounts','MANAGE_ACCOUNTS'],['students','Manage Students','MANAGE_STUDENTS'],['teachers','Manage Teachers','MANAGE_TEACHERS'],['keys','Activation Keys','MANAGE_KEYS'],['badges','Manage Badges','MANAGE_BADGES'],['subjects','Manage Subjects','MANAGE_SUBJECTS'],['schedule','Manage Schedule','MANAGE_SCHEDULE'],['admins','Manage Admins','MANAGE_ADMINS'],['logs','View Logs','VIEW_LOGS'],['attendance','Attendance','MANAGE_ATTENDANCE']];if(Number(S.me?.is_super_admin)===1||S.me?.role==='SUPER_ADMIN')cards.push(['developers','Manage Developers','MANAGE_DEVELOPERS']);return title(t('admin'),'Control center — permissions are separate from Student/Teacher role.')+'<div class="grid c3 admin-cards">'+cards.filter(x=>can(x[2])).map(x=>'<button class="card admin-card" onclick="go(\'admin:'+x[0]+'\')"><span>◈</span><h3>'+x[1]+'</h3><small>Open management</small></button>').join('')+'</div>'}
function teacherCenterV(){return title(t('teacherCenter'),'Teacher tools — not an Admin Center.')+'<div class="grid c3">'+[['assignments','Create assignments','MANAGE_ASSIGNMENTS'],['resources','Publish resources/PDFs','MANAGE_RESOURCES'],['exams','Create exams','MANAGE_EXAMS'],['announcements','Publish announcements','MANAGE_ANNOUNCEMENTS'],['subjects','Manage teaching subjects','MANAGE_SUBJECTS'],['schedule','View schedule','VIEW_CLASS']].filter(x=>can(x[2])).map(x=>'<button class="card admin-card" onclick="go(\''+x[0]+'\')"><span>✦</span><h3>'+x[1]+'</h3></button>').join('')+'</div>'}
function settingsV(){
  const ar=S.lang==='ar';
  return title(t('settings'),ar?'الحساب واللغة والمظهر وربط Google.':'Account, language, theme and Google linking.')+
  '<div class="grid c2"><div class="card"><h3>'+ (ar?'الملف الشخصي':'Profile') +'</h3><form class="form" onsubmit="saveProfile(event)"><label>'+ (ar?'اسم العرض':'Display name') +'<input id="displayName" value="'+esc(S.me?.display_name||'')+'" required></label><label>'+ (ar?'صورة الملف الشخصي':'Profile image') +'<input id="profileAvatar" type="file" accept="image/png,image/jpeg,image/webp"></label><button class="btn primary">'+t('save')+'</button></form><button class="btn ghost" onclick="passwordModal()">'+(ar?'تغيير كلمة المرور':'Change password')+'</button><button class="btn danger" onclick="logout()"> '+t('logout')+'</button></div>'+
  '<div class="card"><h3>'+ (ar?'التفضيلات':'Preferences') +'</h3><div class="settings-lang"><button class="btn '+(S.lang==='en'?'primary':'ghost')+'" onclick="setLang(\'en\')">EN</button><button class="btn '+(S.lang==='ar'?'primary':'ghost')+'" onclick="setLang(\'ar\')">عربي</button></div><button class="btn ghost" onclick="toggleTheme()">'+(S.theme==='dark'?t('light'):t('dark'))+'</button><hr><h3>Google</h3><p class="muted">'+(S.linked.length?(ar?'Google مرتبط':'Google linked'):(ar?'Google غير مرتبط':'Google not linked'))+'</p><button class="btn primary" onclick="googleLink()">'+(S.linked.length?(ar?'إعادة ربط Google':'Relink Google'):(ar?'ربط Google':'Link Google'))+'</button>'+(S.linked.length?'<button class="btn danger" onclick="unlinkGoogle()">'+(ar?'إلغاء ربط Google':'Unlink Google')+'</button>':'')+'</div></div>';
}
function devV(){return title(t('developers'),'The B4 development team and project contributors.')+'<div class="grid developers-grid">'+S.developers.map(d=>'<article class="card developer-card"><div class="developer-photo"><img class="avatar xl" src="'+esc(d.avatar_url||'assets/logo.svg')+'" onerror="this.src=\'assets/logo.svg\'"></div><div class="developer-info"><span class="badge">B4 DEVELOPER</span><h3>'+esc(d.name)+'</h3>'+(d.link_url?'<a class="btn ghost developer-link" href="'+esc(d.link_url)+'" target="_blank" rel="noopener">Open profile ↗</a>':'')+'</div></article>').join('')||'<div class="card empty">No developers added yet.</div>'+'</div>'}
function render(){document.documentElement.dataset.theme=S.theme;document.documentElement.classList.toggle('dark',S.theme==='dark');document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='ar'?'rtl':'ltr';if(window.chatStream){window.chatStream.close();window.chatStream=null}$('#nav').innerHTML=buildNav();let v=S.view;let html=v==='dashboard'?dashboard():v==='students'?studentsV():v==='teachers'?teachersV():v==='subjects'?subjectsV():v==='schedule'?scheduleV():v==='assignments'?tasksV():v==='resources'?resourcesV():v==='exams'?examsV():v==='announcements'?announcementsV():v==='chat'?chatV():v==='teacherChat'?teacherChatV():v==='attendance'?attendanceV():v==='admin'?adminV():v==='teacherCenter'?teacherCenterV():v==='settings'?settingsV():v==='developers'?devV():v==='exam-review'?examReviewV():v.startsWith('admin:')?adminPage(v.slice(6)):dashboard();$('#content').innerHTML=html;$('#topName').textContent=S.me?.display_name||t('guest');if(S.me?.avatar_url)$('#topAvatar').src=S.me.avatar_url;if(v==='attendance'&&can('MANAGE_ATTENDANCE'))attendanceLoad();if(v==='chat')chatLoop();if(v==='teacherChat')teacherChatLoop();if(v.startsWith('admin:'))adminLoad(v.slice(6))}
function teacherChatV(){return title(t('teacherChat'),'Private chat for teachers and authorized staff.')+'<div class="card chat"><div class="messages" id="teacherMessages">'+S.teacherMessages.map(m=>messageHTML(m)).join('')+'</div><div id="teacherTyping" class="typing-indicator"></div><form class="chatform" onsubmit="sendTeacherChat(event)"><input id="teacherInput" oninput="teacherTyping(!!this.value.trim())"><button class="btn primary">➤</button></form></div>'}
function adminPage(p){if(p==='roles')return title('Roles','Account role is only Student or Teacher. Super Admin is a private system flag, never a role.')+'<div id="adminRoot"></div>';if(p==='permissions')return title('Permissions','Direct permissions are independent from the account role. Administrator grants every permission.')+'<div id="adminRoot"></div>';if(p==='accounts')return title('Accounts','Activation key, Google link, password and sessions.')+'<div id="adminRoot"></div>';if(p==='students')return title('Manage Students','Edit identity, display name and photo.','<button class="btn primary" onclick="studentEdit()">＋ Add</button>')+'<div class="grid c3">'+S.students.map(x=>peopleCard(x,'student')).join('')+'</div>';if(p==='teachers')return title('Manage Teachers','Edit identity, display name and photo.','<button class="btn primary" onclick="teacherEdit()">＋ Add</button>')+'<div class="grid c3">'+S.teachers.map(x=>peopleCard(x,'teacher')).join('')+'</div>';if(p==='keys')return title('Activation Keys','One-time keys.')+'<div id="adminRoot"></div>';if(p==='badges')return title('Manage Badges','Create icons and assign badges.')+'<div id="adminRoot"></div>';if(p==='subjects')return subjectsV();if(p==='schedule')return scheduleV();if(p==='admins')return title('Manage Admins','Admin access is independent from Student/Teacher role.')+'<div id="adminRoot"></div>';if(p==='logs')return title('Logs','All platform activity and security events.')+'<div id="adminRoot"></div>';if(p==='attendance')return attendanceV();if(p==='developers')return title('Manage Developers','Super Admin only.')+'<div id="adminRoot"></div>';return adminV()}
async function loadMe(){try{const d=await api('/api/auth/me');S.me=d.user;S.linked=(await api('/api/auth/linked')).linked||[]}catch{S.me=null;S.linked=[]}await loadData();render()}
async function loadData(){try{const d=await api('/api/bootstrap');Object.assign(S,{students:d.students||[],teachers:d.teachers||[],subjects:d.subjects||[],schedule:d.schedule||[],assignments:d.assignments||[],announcements:d.announcements||[],resources:d.resources||[],exams:d.exams||[],attendance:d.attendance||[],messages:d.messages||[],notifications:d.notifications||[]});if(S.me&&(Number(S.me.is_super_admin)===1||S.me.role==='SUPER_ADMIN')){try{S.developers=(await api('/api/admin/developers')).developers||[]}catch{}}S.error=''}catch(e){S.error=e.message}}
async function login(e){e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({login:$('#loginName').value.trim(),password:$('#loginPassword').value})});close();await loadMe();toast('Login successful ✓')}catch(x){toast(x.message)}}
function loginModal(){modal('<div class="modalhead"><h2>'+t('login')+'</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="login(event)"><label>Display name<input id="loginName" required autocomplete="username"></label><label>Password<input id="loginPassword" type="password" required autocomplete="current-password"></label><button class="btn primary">'+t('login')+' →</button></form><div class="login-divider"><span>or</span></div><button class="google-btn" onclick="googleLogin()">Continue with Google</button><button class="btn ghost" onclick="forgotPassword()">Forgot my password</button><button class="btn ghost" onclick="activationModal()">'+t('activate')+'</button>')}
function activationModal(){modal('<div class="modalhead"><h2>'+t('activate')+'</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="activate(event)"><label>One-time key<input id="actKey" required></label><label>Display name<input id="actName" required></label><label>Password<input id="actPw" type="password" minlength="8" required></label><button class="btn primary">Create account</button></form>')}
async function activate(e){e.preventDefault();try{await api('/api/auth/activate',{method:'POST',body:JSON.stringify({key:$('#actKey').value.trim(),displayName:$('#actName').value.trim(),password:$('#actPw').value})});close();toast('Account created ✓');loginModal()}catch(x){toast(x.message)}}
function googleLogin(){location.href=API+'/api/auth/google/login'}
async function openNotifications(){try{const d=await api('/api/bootstrap');const list=d.notifications||[];modal('<div class="modalhead"><h2>Notifications</h2><button class="close" onclick="b4Close()">×</button></div><div class="list">'+(list.length?list.map(n=>'<div class="item"><span class="grow"><b>'+esc(n.title)+'</b><small class="muted">'+esc(n.body||'')+'</small></span><small class="muted">'+esc(n.created_at||'')+'</small></div>').join(''):'<div class="empty">No notifications.</div>')+'</div>')}catch(e){toast(e.message)}}
async function forgotPassword(){try{const d=await api('/api/auth/forgot-password',{method:'POST'});location.href=d.whatsapp}catch(e){toast('WhatsApp support is unavailable')}} 
function passwordModal(){modal('<div class="modalhead"><h2>Change password</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="changePassword(event)"><label>Current password<input id="oldPw" type="password" required></label><label>New password<input id="newPw" type="password" minlength="8" required></label><button class="btn primary">Save</button></form>')}
async function changePassword(e){e.preventDefault();try{await api('/api/auth/password',{method:'POST',body:JSON.stringify({currentPassword:$('#oldPw').value,newPassword:$('#newPw').value})});close();toast('Password changed ✓')}catch(x){toast(x.message)}}
async function saveProfile(e){e.preventDefault();try{await api('/api/auth/profile',{method:'PATCH',body:JSON.stringify({displayName:$('#displayName').value.trim()})});const f=$('#profileAvatar')?.files?.[0];if(f){const fd=new FormData();fd.append('file',f);const r=await fetch(API+'/api/auth/avatar',{method:'POST',credentials:'include',body:fd});if(!r.ok)throw Error('Image upload failed')}await loadMe();toast('Saved ✓')}catch(x){toast(x.message)}}
async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>{});S.me=null;S.view='students';await loadData();render();toast('Logged out')}
function googleLink(){location.href=API+'/api/auth/google/start'}async function unlinkGoogle(){try{await api('/api/auth/linked/GOOGLE',{method:'DELETE'});await loadMe()}catch(e){toast(e.message)}}
function aiModal(){modal('<div class="modalhead"><h2>✦ '+t('ai')+'</h2><button class="close" onclick="b4Close()">×</button></div><div id="aiOut" class="card">Ask a study question.</div><form class="form" onsubmit="askAI(event)"><textarea id="aiInput" rows="4" placeholder="Ask about Telecommunication..."></textarea><button class="btn primary">Send</button></form>')}
async function askAI(e){e.preventDefault();if(!S.me||S.me.role!=='STUDENT'){toast('لازم تكون طالب في B4 عشان تستخدم الـAI');return}try{$('#aiOut').textContent='Thinking…';const d=await api('/api/ai',{method:'POST',body:JSON.stringify({message:$('#aiInput').value})});$('#aiOut').textContent=d.answer}catch(x){toast(x.message)}}
function chatLoop(){clearInterval(window.chatTimer);clearInterval(window.chatTypingTimer);if(window.chatStream){window.chatStream.close();window.chatStream=null}if(!S.me||S.view!=='chat')return;try{window.chatStream=new EventSource(API+'/api/chat/stream',{withCredentials:true});window.chatStream.addEventListener('message',e=>{try{const d=JSON.parse(e.data);if(d.type==='created'&&!S.messages.some(m=>Number(m.id)===Number(d.message.id)))S.messages.push(d.message);else if(d.type==='updated')S.messages=S.messages.map(m=>Number(m.id)===Number(d.message.id)?d.message:m);else if(d.type==='deleted')S.messages=S.messages.filter(m=>Number(m.id)!==Number(d.id));const box=$('#messages');if(box){box.innerHTML=S.messages.map(messageHTML).join('');box.scrollTop=box.scrollHeight}}catch{}});window.chatStream.onerror=()=>{};window.chatTypingTimer=setInterval(async()=>{if(S.view!=='chat')return;try{const ty=await api('/api/chat/typing');const el=$('#typing');if(el)el.textContent=(ty.users||[]).filter(x=>Number(x.user_id)!==Number(S.me.id)).map(x=>x.display_name+' is typing…').join(' • ')}catch{}},1200);}catch{}}async function sendChat(e){
  e.preventDefault();const i=$('#chatInput');if(!i.value.trim())return;
  try{
    await api('/api/chat/messages',{method:'POST',body:JSON.stringify({body:i.value.trim(),replyToId:window.replyTo||null})});
    i.value='';i.placeholder='Write a message...';window.replyTo=null;typing(false);toast('Message sent ✓');
  }catch(x){toast(x.message)}
}
function typing(v){if(!S.me)return;api('/api/chat/typing',{method:'POST',body:JSON.stringify({typing:v})}).catch(()=>{});if(window.typingT)clearTimeout(window.typingT);if(v)window.typingT=setTimeout(()=>typing(false),1600)}
function messageMenu(e,id){e.preventDefault();if(!S.me)return;const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m)return;modal('<div class="modalhead"><h2>Message</h2><button class="close" onclick="b4Close()">×</button></div><button class="btn ghost" onclick="replyMessage('+id+')">Reply</button>'+(Number(m.user_id)===Number(S.me.id)?'<button class="btn ghost" onclick="editMessage('+id+')">Edit</button><button class="btn danger" onclick="deleteMessage('+id+')">Delete</button>':'')+'<button class="btn ghost" onclick="b4Close()">Close</button>')}
function replyMessage(id){const m=S.messages.find(x=>Number(x.id)===Number(id));close();window.replyTo=id;const input=$('#chatInput');if(input){input.value='';input.placeholder='Replying to '+(m?.display_name||'message')+'…';input.focus();}toast('Reply mode enabled')}
async function editMessage(id){const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m)return;modal('<div class="modalhead"><h2>Edit message</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveMessage(event,'+id+')"><textarea id="editMsg" rows="4">'+esc(m.body)+'</textarea><button class="btn primary">Save</button></form>')}
async function saveMessage(e,id){e.preventDefault();try{await api('/api/chat/messages/'+id,{method:'PATCH',body:JSON.stringify({body:$('#editMsg').value})});close();toast('Message updated ✓')}catch(x){toast(x.message)}}
async function deleteMessage(id){if(!confirm('Delete message?'))return;try{await api('/api/chat/messages/'+id,{method:'DELETE'});close();toast('Message deleted ✓')}catch(x){toast(x.message)}}
function teacherChatLoop(){clearInterval(window.teacherTimer);window.teacherTimer=setInterval(async()=>{if(S.view!=='teacherChat')return;try{const d=await api('/api/teacher-chat/messages');S.teacherMessages=d.messages||[];const b=$('#teacherMessages');if(b){b.innerHTML=S.teacherMessages.map(messageHTML).join('');b.scrollTop=b.scrollHeight}const ty=await api('/api/teacher-chat/typing');$('#teacherTyping').textContent=(ty.users||[]).filter(x=>Number(x.user_id)!==Number(S.me.id)).map(x=>x.display_name+' is typing…').join(' • ')}catch{}},1000)}
async function sendTeacherChat(e){e.preventDefault();const i=$('#teacherInput');if(!i.value.trim())return;try{await api('/api/teacher-chat/messages',{method:'POST',body:JSON.stringify({body:i.value.trim()})});i.value='';const d=await api('/api/teacher-chat/messages');S.teacherMessages=d.messages||[];render()}catch(x){toast(x.message)}}
function teacherTyping(v){api('/api/teacher-chat/typing',{method:'POST',body:JSON.stringify({typing:v})}).catch(()=>{})}
async function attendanceLoad(){if(!can('MANAGE_ATTENDANCE'))return;const root=$('#attendanceRoot');if(!root)return;const date=new Date().toISOString().slice(0,10);try{const [d,a]=await Promise.all([api('/api/admin/attendance?date='+date),api('/api/attendance/analysis')]);root.innerHTML='<div class="card"><h3>'+date+'</h3><div class="grid c3"><div class="card"><b>'+Number(d.summary?.present_count||0)+'</b><small>Present</small></div><div class="card"><b>'+Number(d.summary?.absent_count||0)+'</b><small>Absent</small></div><div class="card"><b>'+Number(d.summary?.total_count||0)+'</b><small>Marked</small></div></div><h3>Attendance Analysis</h3><div class="analysis-list">'+(a.students||[]).map(s=>'<div class="analysis-row"><div><b>'+esc(s.display_name)+'</b><small>'+Number(s.present_days||0)+' present • '+Number(s.absent_days||0)+' absent</small></div><div class="analysis-bar"><span style="width:'+Number(s.present_rate||0)+'%"></span></div><strong>'+Number(s.present_rate||0)+'%</strong></div>').join('')+'</div><div class="list">'+d.students.map(s=>'<div class="item"><span class="grow"><b>'+esc(s.display_name)+'</b><small class="muted">'+esc(s.student_code||'')+'</small></span><button class="btn '+(s.status==='PRESENT'?'primary':'ghost')+'" onclick="markAttendance('+s.id+',\'PRESENT\')">Present</button><button class="btn '+(s.status==='ABSENT'?'danger':'ghost')+'" onclick="markAttendance('+s.id+',\'ABSENT\')">Absent</button></div>').join('')+'</div></div>'}catch(e){root.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}}async function markAttendance(id,status){try{await api('/api/admin/attendance',{method:'POST',body:JSON.stringify({userId:id,status,date:new Date().toISOString().slice(0,10)})});attendanceLoad();toast(status)}catch(e){toast(e.message)}}
function adminLoad(p){if(p==='roles')loadRoles();if(p==='permissions')loadPermissions();if(p==='accounts')loadAccounts();if(p==='keys')loadKeys();if(p==='badges')loadBadges();if(p==='admins')loadAdmins();if(p==='logs')loadLogs();if(p==='developers')loadDevelopers()}
async function loadRoles(){
  const r=$('#adminRoot');
  try{
    const d=await api('/api/admin/users');S.users=d.users||[];
    r.innerHTML='<div class="grid c2">'+S.users.map(u=>{
      const linked=u.role==='TEACHER'?(u.teacher_id?'Teacher profile #'+u.teacher_id:'Not linked'):(u.student_id?'Student profile #'+u.student_id:'Not linked');
      const options='<option value="STUDENT" '+(u.role==='STUDENT'?'selected':'')+'>STUDENT</option><option value="TEACHER" '+(u.role==='TEACHER'?'selected':'')+'>TEACHER</option>';
      return '<div class="card role-card"><div class="head"><div><b>'+esc(u.display_name)+'</b><p class="muted">'+esc(u.official_name||'')+'</p></div>'+(Number(u.is_super_admin)===1?'<span class="badge">SUPER ADMIN</span>':'<span class="badge">'+esc(u.role)+'</span>')+'</div><p class="muted">Current link: '+esc(linked)+'</p>'+ (Number(u.is_super_admin)===1?'<div class="notice">Super Admin is a private system flag. This account keeps its Student/Teacher role.</div>':'<label>Account role<select onchange="changeRole('+u.id+',this.value)">'+options+'</select></label>')+'</div>';
    }).join('')+'</div>';
  }catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}
}
async function loadPermissions(){
  const r=$('#adminRoot');
  try{const d=await api('/api/admin/users');S.users=d.users||[];
    r.innerHTML='<div class="grid c2">'+S.users.map(u=>'<div class="card permission-user" data-user-id="'+u.id+'"><div class="head"><div><b>'+esc(u.display_name)+'</b><p class="muted">'+esc(u.role)+'</p></div><span class="badge">'+(u.direct_permissions?.length||0)+' direct</span></div><div class="permission-grid">'+PERMS.map(p=>'<label class="permission-tile '+((u.direct_permissions||[]).includes(p[0])?'is-on':'')+'"><input type="checkbox" data-perm="'+p[0]+'" '+((u.direct_permissions||[]).includes(p[0])?'checked':'')+'><span>'+p[1]+'</span></label>').join('')+'</div><button class="btn primary" onclick="savePermissions('+u.id+')">Save permissions</button></div>').join('')+'</div>';
  }catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}
}
async function changeRole(id,role){
  const user=S.users.find(u=>Number(u.id)===Number(id));if(!user)return;
  if(role==='TEACHER'){
    const opts=S.teachers.map(x=>'<option value="'+x.id+'" '+(Number(x.id)===Number(user.teacher_id)?'selected':'')+'>'+esc(x.display_name)+' • '+esc(x.teacher_code||'')+'</option>').join('');
    modal('<div class="modalhead"><h2>Link Teacher Profile</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveRoleLink(event,'+id+',\'TEACHER\')"><p class="muted">Choose the teacher profile this account represents.</p><select id="roleLink">'+opts+'</select><button class="btn primary">Save Teacher role</button></form>');
  }else{
    const opts=S.students.map(x=>'<option value="'+x.id+'" '+(Number(x.id)===Number(user.student_id)?'selected':'')+'>'+esc(x.display_name)+' • '+esc(x.student_code||'')+'</option>').join('');
    modal('<div class="modalhead"><h2>Link Student Profile</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveRoleLink(event,'+id+',\'STUDENT\')"><p class="muted">Choose the student profile this account represents.</p><select id="roleLink">'+opts+'</select><button class="btn primary">Save Student role</button></form>');
  }
}
async function saveRoleLink(e,id,role){
  e.preventDefault();
  const linkId=Number($('#roleLink').value);
  try{
    const body=role==='TEACHER'?{role,teacherId:linkId}:{role,studentId:linkId};
    await api('/api/admin/users/'+id+'/role',{method:'PATCH',body:JSON.stringify(body)});
    close();await loadMe();await loadRoles();toast('Role and profile link updated ✓');
  }catch(e){toast(e.message)}
}
async function savePermissions(id){try{const card=[...document.querySelectorAll('.permission-user')].find(x=>x.dataset.userId===String(id));const codes=card?[...card.querySelectorAll('[data-perm]:checked')].map(x=>x.dataset.perm):[];await api('/api/admin/users/'+id+'/permissions',{method:'PUT',body:JSON.stringify({permissionCodes:codes})});toast('Permissions saved ✓');loadPermissions()}catch(e){toast(e.message)}}
async function loadAccounts(){
  const r=$('#adminRoot');
  try{
    const d=await api('/api/admin/accounts');
    r.innerHTML=`<div class="tablewrap"><table class="table"><thead><tr><th>Name</th><th>Role</th><th>Activation</th><th>Google</th><th>Session</th><th>Actions</th></tr></thead><tbody>
      ${(d.accounts||[]).map(a=>`<tr><td>${esc(a.display_name)}</td><td>${esc(a.role)}</td><td>${esc(a.activation_key_preview||a.identity_code||'—')}</td><td>${a.google_linked?'✓':'—'}</td><td>${esc(a.status)}</td><td><button class="btn ghost" onclick="resetAccount(${a.id})">Reset password</button><button class="btn ghost" onclick="endSession(${a.id})">End session</button><button class="btn danger" onclick="deleteAccount(${a.id})">Delete</button></td></tr>`).join('')}
    </tbody></table></div>`;
  }catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}
}
async function deleteAccount(id){
  if(!confirm('Delete this account permanently?'))return;
  try{await api('/api/admin/accounts/'+id,{method:'DELETE'});await loadData();loadAccounts();toast('Account deleted ✓')}catch(e){toast(e.message)}
}
async function resetAccount(id){try{const d=await api('/api/admin/accounts/'+id+'/reset-password',{method:'POST'});modal('<div class="modalhead"><h2>Temporary password</h2><button class="close" onclick="b4Close()">×</button></div><div class="notice"><b>'+esc(d.tempPassword)+'</b></div><p class="muted">Give it to the account owner and ask them to change it.</p>')}catch(e){toast(e.message)}}
async function endSession(id){try{await api('/api/admin/accounts/'+id+'/end-session',{method:'POST'});toast('Session ended ✓')}catch(e){toast(e.message)}}
async function loadKeys(){
  const r=$('#adminRoot');
  try{
    const d=await api('/api/admin/activation-keys');
    r.innerHTML=`<div class="head"><div><h3>Activation keys</h3><p class="muted">Copy and revoke keys.</p></div><button class="btn primary" onclick="createKey()">＋ Generate key</button></div>
      <div class="list">${(d.keys||[]).map(k=>`<div class="item key-row"><span class="grow"><b>${esc(k.key_value||k.key_preview)}</b><small>${esc(k.person_name||'')} • ${esc(k.person_type||'')}</small></span><span class="badge">${esc(k.status)}</span>${k.key_value?'<button class="btn ghost" onclick="copyKey('+k.id+')">Copy</button>':''}${k.status==='ACTIVE'?'<button class="btn danger" onclick="revokeKey('+k.id+')">Revoke</button>':''}</div>`).join('')||'<div class="card empty">No activation keys yet.</div>'}</div>`;
  }catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}
}
async function copyKey(id){
  try{const d=await api('/api/admin/activation-keys');const k=(d.keys||[]).find(x=>Number(x.id)===Number(id));if(!k?.key_value)return toast('This older key cannot be recovered');await navigator.clipboard.writeText(k.key_value);toast('Activation key copied ✓')}catch(e){toast(e.message)}
}
async function revokeKey(id){
  if(!confirm('Revoke this activation key?'))return;
  try{await api('/api/admin/activation-keys/'+id+'/revoke',{method:'POST'});loadKeys();toast('Key revoked ✓')}catch(e){toast(e.message)}
}
async function createKey(){try{const d=await api('/api/admin/people');const opts=[...d.students.map(x=>'<option value="STUDENT:'+x.id+'">'+esc(x.display_name)+'</option>'),...d.teachers.map(x=>'<option value="TEACHER:'+x.id+'">'+esc(x.display_name)+'</option>')].join('');modal('<div class="modalhead"><h2>Generate activation key</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="makeKey(event)"><select id="keyPerson">'+opts+'</select><button class="btn primary">Generate</button></form>')}catch(e){toast(e.message)}}
async function makeKey(e){e.preventDefault();const [personType,personId]=$('#keyPerson').value.split(':');try{const d=await api('/api/admin/activation-keys',{method:'POST',body:JSON.stringify({personType,personId:Number(personId)})});close();await navigator.clipboard?.writeText(d.key);modal('<div class="modalhead"><h2>Activation key</h2><button class="close" onclick="b4Close()">×</button></div><div class="notice mono">'+esc(d.key)+'</div>')}catch(x){toast(x.message)}}
async function loadBadges(){const r=$('#adminRoot');try{const d=await api('/api/admin/badges');S.badges=d.badges||[];r.innerHTML='<button class="btn primary" onclick="badgeCreate()">＋ Add badge</button><div class="grid c3">'+d.badges.map(b=>'<article class="card"><img class="avatar" src="/api/badges/'+b.id+'/icon"><h3>'+esc(b.name)+'</h3><p>'+esc(b.description||'')+'</p><button class="btn ghost" onclick="badgeAssign('+b.id+')">Assign</button></article>').join('')+'</div>'}catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}}
function badgeCreate(){modal('<div class="modalhead"><h2>New badge</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="makeBadge(event)"><input id="badgeName" placeholder="Badge name" required><input id="badgeDesc" placeholder="Description"><input id="badgeIcon" type="file" accept="image/*"><button class="btn primary">Create</button></form>')}
async function makeBadge(e){e.preventDefault();try{const d=await api('/api/admin/badges',{method:'POST',body:JSON.stringify({name:$('#badgeName').value,description:$('#badgeDesc').value})});const f=$('#badgeIcon').files[0];if(f){const fd=new FormData();fd.append('file',f);await fetch(API+'/api/admin/badges/'+d.id+'/icon',{method:'POST',credentials:'include',body:fd})}close();loadBadges()}catch(x){toast(x.message)}}
async function badgeAssign(bid){const d=await api('/api/admin/badges');const opts=d.people.map(p=>'<option value="'+p.id+'">'+esc(p.display_name)+' • '+p.role+'</option>').join('');modal('<div class="modalhead"><h2>Assign badge</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="doBadgeAssign(event,'+bid+')"><select id="badgeUser">'+opts+'</select><button class="btn primary">Assign</button></form>')}
async function doBadgeAssign(e,bid){e.preventDefault();try{await api('/api/admin/badges/assign',{method:'POST',body:JSON.stringify({userId:Number($('#badgeUser').value),badgeId:bid})});close();toast('Badge assigned ✓')}catch(x){toast(x.message)}}
async function loadAdmins(){const r=$('#adminRoot');const d=await api('/api/admin/users');r.innerHTML='<div class="grid c2">'+d.users.filter(u=>u.role!=='SUPER_ADMIN').map(u=>'<div class="card"><b>'+esc(u.display_name)+'</b><p class="muted">'+esc(u.role)+'</p><button class="btn primary" onclick="adminPermissions('+u.id+')">Manage admin access</button></div>').join('')+'</div><button class="btn ghost" onclick="adminPermissions()">Grant to a person</button>'}
async function adminPermissions(id){const d=await api('/api/admin/users');const opts=d.users.filter(u=>u.role!=='SUPER_ADMIN').map(u=>'<option value="'+u.id+'">'+esc(u.display_name)+' • '+u.role+'</option>').join('');modal('<div class="modalhead"><h2>Admin access</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="grantAdmin(event)"><select id="adminUser">'+opts+'</select><div class="permission-grid">'+PERMS.map(p=>'<label class="permission-tile"><input type="checkbox" name="ap" value="'+p[0]+'"><span>'+p[1]+'</span></label>').join('')+'</div><button class="btn primary">Save admin permissions</button></form>')}
async function grantAdmin(e){e.preventDefault();const id=Number($('#adminUser').value),codes=[...document.querySelectorAll('input[name="ap"]:checked')].map(x=>x.value);try{await api('/api/admin/users/'+id+'/permissions',{method:'PUT',body:JSON.stringify({permissionCodes:codes})});close();toast('Admin access saved ✓')}catch(x){toast(x.message)}}
async function loadLogs(){const r=$('#adminRoot');try{const d=await api('/api/admin/logs');r.innerHTML='<div class="list">'+[...(d.activity||[]),...(d.security||[])].map(x=>'<div class="item"><span class="grow"><b>'+esc(x.action)+'</b><small>'+esc(x.actor_name||'System')+' • '+esc(x.created_at||'')+'</small></span></div>').join('')+'</div>'}catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}}
async function loadDevelopers(){
  const r=$('#adminRoot');
  try{
    const d=await api('/api/admin/developers');S.developers=d.developers||[];
    r.innerHTML=`<div class="head"><div><h3>Developers</h3><p class="muted">Name, photo and profile link.</p></div><button class="btn primary" onclick="developerEdit()">＋ Add developer</button></div>
      <div class="grid developers-grid">${S.developers.map(x=>`<article class="card developer-card"><img class="avatar xl" src="${esc(x.avatar_url||'assets/logo.svg')}" onerror="this.src='assets/logo.svg'"><div class="developer-info"><h3>${esc(x.name)}</h3>${x.link_url?`<a class="btn ghost developer-link" href="${esc(x.link_url)}" target="_blank" rel="noopener">Open link ↗</a>`:''}<div class="actions-row"><button class="btn ghost" onclick="developerEdit(${x.id})">Edit</button><button class="btn danger" onclick="developerDelete(${x.id})">Delete</button></div></div></article>`).join('')||'<div class="card empty">No developers yet.</div>'}</div>`;
  }catch(e){r.innerHTML='<div class="card notice">'+esc(e.message)+'</div>'}
}
function developerEdit(id){
  const x=(S.developers||[]).find(d=>Number(d.id)===Number(id))||{};
  modal('<div class="modalhead"><h2>'+(id?'Edit':'Add')+' developer</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveDeveloper(event,'+(id||'null')+')"><label>Name<input id="devName" value="'+esc(x.name||'')+'" placeholder="Developer name" required></label><label>Profile / Discord / GitHub link<input id="devLink" type="url" value="'+esc(x.link_url||'')+'" placeholder="https://..."></label><label>Photo<input id="devAvatar" type="file" accept="image/*"></label><button class="btn primary">Save developer</button></form>')
}
async function saveDeveloper(e,id){
  e.preventDefault();
  try{
    const d=await api(id?'/api/admin/developers/'+id:'/api/admin/developers',{method:id?'PATCH':'POST',body:JSON.stringify({name:$('#devName').value,linkUrl:$('#devLink').value})});
    const f=$('#devAvatar').files[0];
    if(f){const fd=new FormData();fd.append('file',f);const rr=await fetch(API+'/api/admin/developers/'+(id||d.id)+'/avatar',{method:'POST',credentials:'include',body:fd});if(!rr.ok)throw Error('Developer image upload failed')}
    close();loadDevelopers()
  }catch(x){toast(x.message)}
}
async function developerDelete(id){if(confirm('Delete developer?')){await api('/api/admin/developers/'+id,{method:'DELETE'});loadDevelopers()}}
function studentEdit(id){const x=(S.students||[]).find(s=>Number(s.id)===Number(id))||{};modal('<div class="modalhead"><h2>'+ (id?'Edit student':'Add student')+'</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveStudent(event,'+(id||'null')+')"><input id="sc" value="'+esc(x.student_code||'')+'" placeholder="Student code" required><input id="so" value="'+esc(x.official_name||'')+'" placeholder="Official name" required><input id="sd" value="'+esc(x.display_name||'')+'" placeholder="Display name" required><input id="sa" type="file" accept="image/*"><button class="btn primary">Save</button></form>')}
async function saveStudent(e,id){e.preventDefault();try{let d;if(id)d=await api('/api/admin/students/'+id,{method:'PATCH',body:JSON.stringify({studentCode:$('#sc').value,officialName:$('#so').value,displayName:$('#sd').value})});else d=await api('/api/admin/students',{method:'POST',body:JSON.stringify({studentCode:$('#sc').value,officialName:$('#so').value,displayName:$('#sd').value})});const f=$('#sa').files[0];if(f){const fd=new FormData();fd.append('file',f);await fetch(API+'/api/admin/students/'+(id||d.id)+'/avatar',{method:'POST',credentials:'include',body:fd})}close();await loadData();render()}catch(x){toast(x.message)}}
function teacherEdit(id){const x=(S.teachers||[]).find(s=>Number(s.id)===Number(id))||{};modal('<div class="modalhead"><h2>'+ (id?'Edit teacher':'Add teacher')+'</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveTeacher(event,'+(id||'null')+')"><input id="tc" value="'+esc(x.teacher_code||'')+'" placeholder="Teacher code" required><input id="to" value="'+esc(x.official_name||'')+'" placeholder="Official name" required><input id="td" value="'+esc(x.display_name||'')+'" placeholder="Display name" required><input id="ta" type="file" accept="image/*"><button class="btn primary">Save</button></form>')}
async function saveTeacher(e,id){e.preventDefault();try{let d;if(id)d=await api('/api/admin/teachers/'+id,{method:'PATCH',body:JSON.stringify({teacherCode:$('#tc').value,officialName:$('#to').value,displayName:$('#td').value})});else d=await api('/api/admin/teachers',{method:'POST',body:JSON.stringify({teacherCode:$('#tc').value,officialName:$('#to').value,displayName:$('#td').value})});const f=$('#ta').files[0];if(f){const fd=new FormData();fd.append('file',f);await fetch(API+'/api/admin/teachers/'+(id||d.id)+'/avatar',{method:'POST',credentials:'include',body:fd})}close();await loadData();render()}catch(x){toast(x.message)}}
async function studentDelete(id){if(!confirm('Delete student?'))return;try{await api('/api/admin/students/'+id,{method:'DELETE'});await loadData();render()}catch(e){toast(e.message)}}
async function teacherDelete(id){if(!confirm('Delete teacher?'))return;await api('/api/admin/teachers/'+id,{method:'DELETE'});await loadData();render()}
function subjectEdit(id){const x=S.subjects.find(s=>Number(s.id)===Number(id))||{};modal('<div class="modalhead"><h2>Subject</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveSubject(event,'+(id||'null')+')"><input id="sn" value="'+esc(x.name||'')+'" placeholder="Subject name" required><input id="st" value="'+esc(x.teacher_name||'')+'" placeholder="Teacher"><input id="sp" type="number" min="0" max="100" value="'+(x.progress||0)+'" placeholder="Progress"><button class="btn primary">Save</button></form>')}
async function saveSubject(e,id){e.preventDefault();try{await api(id?'/api/admin/subjects/'+id:'/api/admin/subjects',{method:id?'PATCH':'POST',body:JSON.stringify({name:$('#sn').value,teacherName:$('#st').value,progress:Number($('#sp').value||0)})});close();await loadData();render()}catch(x){toast(x.message)}}
async function subjectDelete(id){if(confirm('Delete subject?')){await api('/api/admin/subjects/'+id,{method:'DELETE'});await loadData();render()}}
function scheduleEdit(){let rows=S.schedule.length?S.schedule: [1,2,3,4,5].map(i=>({day_name:'Day '+i}));modal('<div class="modalhead"><h2>Schedule</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveSchedule(event)">'+rows.map((r,i)=>'<div class="schedule-row"><input id="d'+i+'" value="'+esc(r.day_name||'')+'"><input id="p1'+i+'" value="'+esc(r.p1||'')+'"><input id="p2'+i+'" value="'+esc(r.p2||'')+'"><input id="p3'+i+'" value="'+esc(r.p3||'')+'"><input id="p4'+i+'" value="'+esc(r.p4||'')+'"></div>').join('')+'<button class="btn primary">Save schedule</button></form>')}
async function saveSchedule(e){e.preventDefault();const rows=[...document.querySelectorAll('.schedule-row')].map((r,i)=>({day_name:$('#d'+i).value,p1:$('#p1'+i).value,p2:$('#p2'+i).value,p3:$('#p3'+i).value,p4:$('#p4'+i).value}));try{await api('/api/admin/schedule',{method:'PUT',body:JSON.stringify({schedule:rows})});close();await loadData();render()}catch(x){toast(x.message)}}
function assignmentEdit(id){const x=S.assignments.find(a=>Number(a.id)===Number(id))||{};modal('<div class="modalhead"><h2>Assignment</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveAssignment(event,'+(id||'null')+')"><input id="at" value="'+esc(x.title||'')+'" placeholder="Title" required><select id="as">'+S.subjects.map(s=>'<option value="'+s.id+'" '+(Number(s.id)===Number(x.subject_id)?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select><textarea id="ad">'+esc(x.description||'')+'</textarea><input id="due" type="datetime-local" value="'+(x.due_at?String(x.due_at).slice(0,16):'')+'"><button class="btn primary">Save</button></form>')}
async function saveAssignment(e,id){e.preventDefault();const b={title:$('#at').value,subjectId:Number($('#as').value)||null,description:$('#ad').value,dueAt:$('#due').value||null};try{await api(id?'/api/admin/assignments/'+id:'/api/admin/assignments',{method:id?'PATCH':'POST',body:JSON.stringify(b)});close();await loadData();render()}catch(x){toast(x.message)}}
async function resourceEdit(id){
  const x=S.resources.find(a=>Number(a.id)===Number(id))||{};
  modal('<div class="modalhead"><h2>'+(id?'Edit resource':'New resource')+'</h2><button class="close" onclick="b4Close()">×</button></div>'+
    '<form class="form" onsubmit="saveResource(event,'+(id||'null')+')">'+
    '<label>Title<input id="rt" value="'+esc(x.title||'')+'" placeholder="Resource title" required></label>'+
    '<label>Subject<select id="rs">'+S.subjects.map(s=>'<option value="'+s.id+'" '+(Number(s.id)===Number(x.subject_id)?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label>'+
    '<label>Description<textarea id="rd" rows="3">'+esc(x.description||'')+'</textarea></label>'+
    '<label>Link (optional)<input id="ru" value="'+esc(x.url||'')+'" placeholder="https://..."></label>'+
    '<label>PDF (optional)<input id="rf" type="file" accept="application/pdf"><small class="muted">PDF files up to 15 MB.</small></label>'+
    (x.filename?'<div class="notice">Current PDF: '+esc(x.filename)+'</div>':'')+
    '<button class="btn primary">'+(id?'Save changes':'Publish resource')+'</button></form>');
}
async function saveResource(e,id){
  e.preventDefault();
  try{
    const file=$('#rf')?.files?.[0];
    let resourceId=id;
    if(id){
      await api('/api/admin/resources/'+id,{method:'PATCH',body:JSON.stringify({title:$('#rt').value,description:$('#rd').value,url:$('#ru').value,subjectId:Number($('#rs').value)||null})});
    }else{
      const d=await api('/api/admin/resources',{method:'POST',body:JSON.stringify({title:$('#rt').value,description:$('#rd').value,url:$('#ru').value,subjectId:Number($('#rs').value)||null,resourceType:file?'FILE':'LINK'})});
      resourceId=d.id;
    }
    if(file){
      const fd=new FormData();fd.append('file',file);
      const rr=await fetch(API+'/api/admin/resources/'+resourceId+'/pdf',{method:'POST',credentials:'include',body:fd});
      let rd={};try{rd=await rr.json()}catch{}
      if(!rr.ok)throw Error(rd.error||'PDF upload failed');
    }
    close();await loadData();render();toast('Resource saved ✓');
  }catch(x){toast(x.message)}
}
function announcementEdit(id){const x=S.announcements.find(a=>Number(a.id)===Number(id))||{};modal('<div class="modalhead"><h2>Announcement</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveAnnouncement(event,'+(id||'null')+')"><input id="nt" value="'+esc(x.title||'')+'" placeholder="Title" required><input id="nc" value="'+esc(x.category||'General')+'" placeholder="Category"><textarea id="nb" required>'+esc(x.body||'')+'</textarea><button class="btn primary">Publish</button></form>')}
async function saveAnnouncement(e,id){e.preventDefault();try{await api(id?'/api/admin/announcements/'+id:'/api/admin/announcements',{method:id?'PATCH':'POST',body:JSON.stringify({title:$('#nt').value,category:$('#nc').value,body:$('#nb').value})});close();await loadData();render()}catch(x){toast(x.message)}}
let examDraft=[];
function examInputDate(v){return v?String(v).replace(' ','T').slice(0,16):''}
function examDraftFromQuestion(q){return {questionText:q?.question_text||'',questionType:q?.question_type||'MCQ',options:Array.isArray(q?.options_json)?q.options_json:[],correctAnswer:q?.correct_answer||'',points:Number(q?.points||1)}}
function examQuestionHTML(q,i){
  const type=q.questionType||'MCQ';
  const options=(q.options||['Option A','Option B']).map(x=>String(x||''));
  const optionFields=type==='MCQ'?'<div class="answer-list">'+[0,1,2,3].map(j=>'<div class="answer-option"><input data-qopt="'+i+'" data-opt="'+j+'" value="'+esc(options[j]||'')+'" placeholder="Option '+String.fromCharCode(65+j)+'"><button type="button" class="btn ghost" onclick="setExamCorrect('+i+','+j+')">'+(String(q.correctAnswer||'')===String(options[j]||'')?'✓ Correct':'Set correct')+'</button></div>').join('')+'</div>':
    type==='TRUE_FALSE'?'<div class="answer-list"><label class="answer-option"><input type="radio" name="correct-'+i+'" '+(q.correctAnswer==='TRUE'?'checked':'')+' onchange="examDraft['+i+'].correctAnswer=\'TRUE\'"> TRUE</label><label class="answer-option"><input type="radio" name="correct-'+i+'" '+(q.correctAnswer==='FALSE'?'checked':'')+' onchange="examDraft['+i+'].correctAnswer=\'FALSE\'"> FALSE</label></div>':
    '<label>Correct answer (optional)<input data-qshort="'+i+'" value="'+esc(q.correctAnswer||'')+'" placeholder="Exact answer for automatic grading"></label>';
  return '<article class="card exam-question question-editor" data-qindex="'+i+'"><div class="head"><div><span class="question-number">Question '+(i+1)+'</span><h3>'+esc(q.questionText||'')+'</h3></div><button type="button" class="btn danger" onclick="removeExamQuestion('+i+')">Remove</button></div><label>Question<textarea data-qtext="'+i+'" rows="3" placeholder="Write the question...">'+esc(q.questionText||'')+'</textarea></label><div class="grid c2"><label>Type<select data-qtype="'+i+'" onchange="examTypeChanged('+i+',this.value)"><option value="MCQ" '+(type==='MCQ'?'selected':'')+'>Multiple choice</option><option value="TRUE_FALSE" '+(type==='TRUE_FALSE'?'selected':'')+'>True / False</option><option value="SHORT" '+(type==='SHORT'?'selected':'')+'>Short answer</option></select></label><label>Points<input type="number" min="0.5" step="0.5" data-qpoints="'+i+'" value="'+Number(q.points||1)+'"></label></div>'+optionFields+'</article>';
}
function renderExamQuestions(){const root=$('#examQuestions');if(root)root.innerHTML=examDraft.map(examQuestionHTML).join('')||'<div class="empty">No questions yet. Add one.</div>'}
function addExamQuestion(){collectExamQuestions();examDraft.push({questionText:'',questionType:'MCQ',options:['','','',''],correctAnswer:'',points:1});renderExamQuestions()}
function removeExamQuestion(i){collectExamQuestions();if(examDraft.length<=1)return toast('An exam needs at least one question');examDraft.splice(i,1);renderExamQuestions()}
function setExamCorrect(i,j){collectExamQuestions();examDraft[i].correctAnswer=String(examDraft[i].options[j]||'').trim();renderExamQuestions()}
function examTypeChanged(i,type){collectExamQuestions();examDraft[i].questionType=type;examDraft[i].correctAnswer=type==='TRUE_FALSE'?'TRUE':'';if(type==='MCQ'&&examDraft[i].options.length<4)examDraft[i].options=['','','',''];renderExamQuestions()}
function collectExamQuestions(){
  document.querySelectorAll('[data-qindex]').forEach(card=>{
    const i=Number(card.dataset.qindex);if(!examDraft[i])return;
    examDraft[i].questionText=card.querySelector('[data-qtext]')?.value?.trim()||'';
    examDraft[i].points=Number(card.querySelector('[data-qpoints]')?.value||1);
    const type=card.querySelector('[data-qtype]')?.value||examDraft[i].questionType;examDraft[i].questionType=type;
    if(type==='MCQ'){
      examDraft[i].options=[...card.querySelectorAll('[data-qopt="'+i+'"]')].map(x=>x.value.trim()).filter(Boolean);
    }else if(type==='SHORT') examDraft[i].correctAnswer=card.querySelector('[data-qshort]')?.value?.trim()||'';
  });
}
async function examEdit(id){
  let x=S.exams.find(a=>Number(a.id)===Number(id))||{}, questions=[];
  if(id){try{const d=await api('/api/exams/'+id+'/edit');x=d.exam;questions=(d.questions||[]).map(examDraftFromQuestion)}catch(e){return toast(e.message)}}
  examDraft=questions.length?questions:[{questionText:'',questionType:'MCQ',options:['','','',''],correctAnswer:'',points:1}];
  modal('<div class="modalhead"><h2>'+(id?'Edit exam':'Create exam')+'</h2><button class="close" onclick="b4Close()">×</button></div><form class="form" onsubmit="saveExam(event,'+(id||'null')+')"><label>Title<input id="et" value="'+esc(x.title||'')+'" required></label><label>Subject<select id="es">'+S.subjects.map(s=>'<option value="'+s.id+'" '+(Number(s.id)===Number(x.subject_id)?'selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label><label>Description<textarea id="ed" rows="3">'+esc(x.description||'')+'</textarea></label><div class="grid c2"><label>Start<input id="est" type="datetime-local" value="'+examInputDate(x.starts_at)+'"></label><label>Deadline<input id="een" type="datetime-local" value="'+examInputDate(x.ends_at)+'"></label></div><label>Time limit (minutes)<input id="dur" type="number" min="1" value="'+esc(x.duration_minutes||'')+'" placeholder="Optional"></label><div class="head"><h3>Questions</h3><button type="button" class="btn ghost" onclick="addExamQuestion()">＋ Add question</button></div><div id="examQuestions"></div><button class="btn primary">Save exam</button></form>');
  renderExamQuestions();
}
async function saveExam(e,id){
  e.preventDefault();collectExamQuestions();
  const qs=examDraft.map(q=>({questionText:q.questionText,questionType:q.questionType,options:q.questionType==='MCQ'?q.options:[],correctAnswer:q.correctAnswer||null,points:Number(q.points||1)})).filter(q=>q.questionText);
  if(!qs.length)return toast('Add at least one question');
  if(qs.some(q=>q.questionType==='MCQ'&&(!q.options||q.options.length<2||!q.correctAnswer)))return toast('Each MCQ needs at least 2 options and a correct answer');
  if(qs.some(q=>q.questionType==='TRUE_FALSE'&&!q.correctAnswer))return toast('Choose TRUE or FALSE for every true/false question');
  const b={title:$('#et').value.trim(),description:$('#ed').value,subjectId:Number($('#es').value)||null,startsAt:$('#est').value||null,endsAt:$('#een').value||null,durationMinutes:Number($('#dur').value)||null,questions:qs};
  try{await api(id?'/api/admin/exams/'+id:'/api/admin/exams',{method:id?'PATCH':'POST',body:JSON.stringify(b)});close();await loadData();render();toast('Exam saved ✓')}catch(x){toast(x.message)}
}
async function startExam(id){
  try{
    const d=await api('/api/exams/'+id+'/start',{method:'POST'});
    const questions=d.questions||[];
    modal('<div class="modalhead"><div><span class="eyebrow">EXAM</span><h2>'+esc(d.exam.title)+'</h2></div><button class="close" onclick="b4Close()">×</button></div><div id="examTimer" class="exam-timer">Loading timer…</div><form class="form exam-run-list" id="examRunForm" onsubmit="submitExam(event,'+id+')">'+questions.map((q,i)=>{
      const type=q.question_type||'MCQ',opts=q.options_json||[];
      let body=type==='MCQ'?'<div class="answer-list">'+opts.map((o,j)=>'<label class="answer-option"><input type="radio" name="q'+q.id+'" value="'+esc(o)+'"> <span>'+esc(o)+'</span></label>').join('')+'</div>':
        type==='TRUE_FALSE'?'<div class="answer-list"><label class="answer-option"><input type="radio" name="q'+q.id+'" value="TRUE"> TRUE</label><label class="answer-option"><input type="radio" name="q'+q.id+'" value="FALSE"> FALSE</label></div>':
        '<textarea name="q'+q.id+'" rows="3" placeholder="Your answer..."></textarea>';
      return '<article class="card exam-run-question"><span class="question-number">Question '+(i+1)+' • '+esc(type)+'</span><h3>'+esc(q.question_text)+'</h3>'+body+'</article>';
    }).join('')+'<button id="examSubmitBtn" class="btn primary">Submit exam</button></form>');
    startExamTimer(d.attempt?.deadline,id);
  }catch(e){toast(e.message)}
}
function startExamTimer(deadline,id){
  clearInterval(window.examTimer);
  const box=$('#examTimer'),end=deadline?new Date(deadline).getTime():null;
  const tick=()=>{
    if(!box)return clearInterval(window.examTimer);
    if(!end){box.textContent='No time limit';return}
    const left=Math.max(0,end-Date.now()),sec=Math.floor(left/1000),m=Math.floor(sec/60),s=sec%60;
    box.textContent='Time remaining • '+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');
    box.classList.toggle('warn',left<60000);box.classList.toggle('danger',left<15000);
    if(left<=0){clearInterval(window.examTimer);toast('Time is over — submitting exam');const form=$('#examRunForm');if(form)submitExam({preventDefault:()=>{}},id,true);}
  };
  tick();window.examTimer=setInterval(tick,1000);
}
async function submitExam(e,id,auto=false){
  e.preventDefault?.();clearInterval(window.examTimer);
  const form=$('#examRunForm'),answers={};
  if(form)form.querySelectorAll('[name^="q"]').forEach(x=>{if((x.type==='radio'&&x.checked)||x.type==='textarea'||(x.type!=='radio'&&x.value?.trim()))answers[x.name.slice(1)]=x.value.trim()});
  try{const d=await api('/api/exams/'+id+'/submit',{method:'POST',body:JSON.stringify({answers})});const pct=Number(d.percent||0);modal('<div class="modalhead"><h2>Exam result</h2><button class="close" onclick="b4Close()">×</button></div><div class="score-wrap"><div class="score-ring" style="--score:'+pct+'"><svg viewBox="0 0 120 120"><circle class="score-bg" cx="60" cy="60" r="50"></circle><circle class="score-value" cx="60" cy="60" r="50" pathLength="100" stroke-dasharray="'+pct+' 100"></circle></svg><div class="score-number">'+pct+'%<small>'+d.score+' / '+d.total+'</small></div></div><p>'+(auto?'Auto-submitted because the time limit ended.':'Submitted successfully.')+'</p></div>')}catch(x){toast(x.message)}
}
async function submissions(id){try{const d=await api('/api/admin/exams/'+id+'/submissions');S.examReview={examId:id,submissions:d.submissions||[]};S.view='exam-review';render();}catch(e){toast(e.message)}}
async function openExamSubmission(examId,attemptId){try{const d=await api('/api/admin/exams/'+examId+'/submissions/'+attemptId);S.examReview={examId,detail:d};S.view='exam-review';render();}catch(e){toast(e.message)}}
function examReviewV(){const r=S.examReview||{};if(r.detail){const d=r.detail;return title('Submission review','Answers submitted by '+esc(d.attempt?.display_name||'Student'),'<button class="btn ghost" onclick="go(\'exams\')">← Back</button>')+'<div class="grid c3 review-summary"><div class="card"><small>Student</small><b>'+esc(d.attempt?.display_name||'—')+'</b></div><div class="card"><small>Score</small><b>'+Number(d.attempt?.score||0)+' / '+Number(d.total||0)+'</b></div><div class="card"><small>Percentage</small><b>'+Number(d.percent||0)+'%</b></div></div><div class="grid review-questions">'+(d.questions||[]).map((q,i)=>'<article class="card review-question"><div class="head"><span class="question-number">Question '+(i+1)+'</span><span class="badge">'+esc(q.question_type)+'</span></div><h3>'+esc(q.question_text)+'</h3><div class="answer-block"><small>Student answer</small><p>'+esc(q.answer_text||'No answer')+'</p></div><div class="answer-block"><small>Correct answer</small><p>'+esc(q.correct_answer||'Not auto-graded')+'</p></div><div class="answer-result '+(q.is_correct===null||q.is_correct===undefined?'not-graded':(q.is_correct?'correct':'incorrect'))+'">'+(q.is_correct===null||q.is_correct===undefined?'• Not auto-graded':(q.is_correct?'✓ Correct':'✕ Incorrect')+' • '+Number(q.points_awarded||0)+' / '+Number(q.points||0))+'</div></article>').join('')+'</div>'}
return title('Exam submissions','Choose a student to review their full answers.','<button class="btn ghost" onclick="go(\'exams\')">← Back</button>')+'<div class="grid review-submissions">'+(r.submissions||[]).map(x=>'<button class="card review-student" onclick="openExamSubmission('+r.examId+','+x.id+')"><div><b>'+esc(x.display_name)+'</b><small>'+esc(x.status||'')+'</small></div><span class="badge">'+Number(x.percent||0)+'%</span></button>').join('')||'<div class="card empty">No submissions yet.</div>'+'</div>'}
async function delAPI(path,msg){if(!confirm('Are you sure?'))return;try{await api(path,{method:'DELETE'});await loadData();render();toast(msg+' ✓')}catch(e){toast(e.message)}}
function searchBind(){const i=$('#search');if(i)i.oninput=()=>{const q=i.value.toLowerCase().trim();if(!q)return;const all=[...S.students,...S.teachers,...S.subjects,...S.assignments,...S.resources];const x=all.find(a=>String(a.display_name||a.name||a.title||'').toLowerCase().includes(q));if(x)toast('Found: '+(x.display_name||x.name||x.title))}}
function toggleTheme(){S.theme=S.theme==='dark'?'light':'dark';localStorage.b4Theme=S.theme;render()}
function setLang(lang){S.lang=lang==='ar'?'ar':'en';localStorage.b4Lang=S.lang;render()}
function toggleLang(){setLang(S.lang==='ar'?'en':'ar')}
function commandCenter(){modal('<div class="modalhead"><h2>More</h2><button class="close" onclick="b4Close()">×</button></div><div class="list"><button class="item" onclick="close();go(\'students\')">Students</button><button class="item" onclick="close();go(\'subjects\')">Subjects</button><button class="item" onclick="close();go(\'schedule\')">Schedule</button><button class="item" onclick="close();go(\'settings\')">Settings</button></div>')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v]');if(b)go(b.dataset.v)});
function cancelReply(){window.replyTo=null;const i=$('#chatInput');if(i){i.value='';i.placeholder='Write a message...'}close()}
window.addEventListener('beforeunload',()=>clearInterval(window.examTimer));
document.addEventListener('DOMContentLoaded',async()=>{document.documentElement.dataset.theme=S.theme;document.documentElement.classList.toggle('dark',S.theme==='dark');$('#theme').onclick=toggleTheme;$('#lang').onclick=toggleLang;$('#install').onclick=()=>toast('Use your browser menu to install B4');$('#mobile').onclick=()=>$('#side').classList.toggle('open');$('#ai').onclick=aiModal;$('#bell').onclick=openNotifications;$('#mobileAlerts').onclick=openNotifications;$('#profile').onclick=()=>S.me?go('settings'):loginModal();searchBind();await loadMe()});
