const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const API_BASE=(window.B4_API_URL||localStorage.b4ApiUrl||'').replace(/\/$/,'');
const api=async(path,opts={})=>{const r=await fetch(API_BASE+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d};
const S={lang:localStorage.b4Lang||'en',theme:localStorage.b4Theme||'light',view:'dashboard',me:null,students:[],subjects:[],tasks:[],announcements:[],messages:[],attendance:[],notifications:[],schedule:[],resources:[],exams:[],activationKeys:[],online:false,dataError:'',linked:[]};
const can=p=>{if(p==='ADMIN_CENTER')return !!S.me&&(['MANAGE_ADMINS','MANAGE_ROLES','MANAGE_ACCOUNTS','MANAGE_STUDENTS','MANAGE_KEYS','MANAGE_SUBJECTS','MANAGE_SCHEDULE','MANAGE_ASSIGNMENTS','MANAGE_RESOURCES','MANAGE_EXAMS','MANAGE_ATTENDANCE','MANAGE_ANNOUNCEMENTS','MANAGE_CHAT','VIEW_LOGS'].some(x=>(S.me.permissions||[]).includes(x)));if(p==='ACCOUNT')return !!S.me;if(!p)return true;return !S.me?p==='VIEW_CLASS':S.me.role==='SUPER_ADMIN'||(S.me.permissions||[]).includes(p)};
const L={en:{dash:'Dashboard',students:'Students',subjects:'Subjects',schedule:'Schedule',tasks:'Assignments',resources:'Resources',exams:'Exam Center',news:'Announcements',chat:'Class Chat',attendance:'Attendance',admin:'Admin Center',settings:'Settings',academic:'ACADEMICS',community:'COMMUNITY',more:'MORE',themeD:'Dark mode',themeL:'Light mode',install:'Install App',search:'Search everything...',welcome:'Welcome to B4 👋',sub:'Telecommunication • your class, academics and communication in one place.',add:'Add',view:'View all',login:'Login',logout:'Logout',activate:'Activation Key',account:'Account',linked:'Linked Accounts',save:'Save',password:'Password',display:'Display name',ai:'B4 AI Assistant'},ar:{dash:'الرئيسية',students:'الطلاب',subjects:'المواد',schedule:'الجدول',tasks:'المهام',resources:'المصادر',exams:'مركز الامتحانات',news:'الإعلانات',chat:'شات الفصل',attendance:'الحضور',admin:'مركز الإدارة',settings:'الإعدادات',academic:'الدراسة',community:'المجتمع',more:'المزيد',themeD:'الوضع الليلي',themeL:'الوضع النهاري',install:'تثبيت التطبيق',search:'ابحث في كل حاجة...',welcome:'أهلاً بك في B4 👋',sub:'اتصالات • دراستك وفصلك وتواصلك في مكان واحد.',add:'إضافة',view:'عرض الكل',login:'تسجيل الدخول',logout:'تسجيل الخروج',activate:'مفتاح التفعيل',account:'الحساب',linked:'الحسابات المرتبطة',save:'حفظ',password:'كلمة المرور',display:'اسم العرض',ai:'مساعد B4 الذكي'}};const t=k=>L[S.lang][k]||k;
const nav=[['dashboard','⌂','dash',null],['g','','academic',null],['students','♙','students','VIEW_CLASS'],['subjects','▣','subjects','VIEW_CLASS'],['schedule','◫','schedule','VIEW_CLASS'],['assignments','✓','tasks','VIEW_CLASS'],['resources','▤','resources','VIEW_CLASS'],['exams','⌁','exams','VIEW_CLASS'],['g','','community',null],['announcements','◈','news','VIEW_CLASS'],['chat','◌','chat','VIEW_CLASS'],['g','','more',null],['attendance','◉','attendance','VIEW_CLASS'],['admin','⚙','admin','ADMIN_CENTER'],['settings','⚙','settings','ACCOUNT']];
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2600)}function close(){$('#back').classList.remove('show')}function modal(h){$('#modal').innerHTML=`<div class="modal">${h}</div>`;$('#back').classList.add('show')}function go(v){S.view=v;render();window.scrollTo({top:0,behavior:'smooth'});$('#side').classList.remove('open')}
function buildNav(){
  let out='',group=[];
  const flush=()=>{if(group.length){out+=group.map(x=>`<button data-v="${x[0]}" class="${S.view===x[0]?'active':''}">${x[1]} <span>${t(x[2])}</span>${x[0]==='assignments'&&S.tasks.length?`<em>${S.tasks.length}</em>`:''}</button>`).join('');group=[]}};
  for(const x of nav){if(x[0]==='g'){flush();out+=`<div class="nav-group">${t(x[2])}</div>`;continue}if(can(x[3]))group.push(x)}
  flush();
  return out;
}
function title(h,p,b=''){return `<div class="title"><div><div class="eyebrow">B4 • TELECOMMUNICATION</div><h1>${h}</h1><p>${p}</p></div><div class="actions">${b}</div></div>`}
function dashboard(){const n=S.me?.display_name||'Guest';return title(`${t('welcome')}`,`${t('sub')} ${S.me?`• ${esc(n)}`:''}`,S.me?`<button class="btn ghost" onclick="go('settings')">⚙ ${t('settings')}</button>`:`<button class="btn primary" onclick="loginModal()">${t('login')}</button>`)+`${S.dataError?`<div class="card notice"><b>Database data could not be loaded.</b><div class="muted">${esc(S.dataError)}</div></div>`:''}<div class="hero"><div class="hero-row"><div><div class="eyebrow" style="color:#fff9">WE SCHOOL • B4</div><h1>B4 Telecommunication</h1><p>${S.lang==='ar'?'منصة الفصل الرسمية للطلاب والمدرسين والإدارة — بدون بيانات تجريبية.':'The official class portal for students, teachers and admins — no demo class data.'}</p><button class="btn" style="background:#fff;color:#6d28d9" onclick="aiModal()">✦ ${t('ai')}</button></div></div></div><div class="grid stats"><div class="card stat"><div><small>${t('students')}</small><b>${S.students.length}</b></div><div class="ico">♙</div></div><div class="card stat"><div><small>${t('subjects')}</small><b>${S.subjects.length}</b></div><div class="ico">▣</div></div><div class="card stat"><div><small>${t('tasks')}</small><b>${S.tasks.length}</b></div><div class="ico">✓</div></div><div class="card stat"><div><small>${t('attendance')}</small><b>${attendanceRate()}%</b></div><div class="ico">◉</div></div></div><div class="grid c2"><div class="card"><div class="head"><h3>${t('news')}</h3><button class="btn ghost" onclick="go('announcements')">${t('view')}</button></div><div class="list">${S.announcements.slice(0,4).map(a=>`<div class="item"><div class="ico">◈</div><div class="grow"><b>${esc(a.title)}</b><div class="muted">${esc(a.body||'')}</div></div></div>`).join('')||`<div class="empty">${S.lang==='ar'?'لا توجد إعلانات حتى الآن':'No announcements yet'}</div>`}</div></div><div class="card"><div class="head"><h3>✦ ${t('ai')}</h3><span class="badge">ONLINE</span></div><p class="muted">${S.lang==='ar'?'اسأل عن دروس الاتصالات، المذاكرة، الواجبات أو الامتحانات.':'Ask about Telecommunication lessons, revision, assignments or exams.'}</p><button class="btn primary" onclick="aiModal()">Ask AI →</button></div></div>`}
function studentsV(){return title(t('students'),S.lang==='ar'?'البيانات الرسمية محفوظة، واسم العرض قابل للتعديل من الحساب.':'Official identity is protected; students can edit only their display profile.',can('MANAGE_STUDENTS')?`<button class="btn primary" onclick="adminStudentModal()">＋ ${t('add')}</button>`:'')+`<div class="grid c3">${S.students.map(s=>`<div class="card"><div class="item" style="padding:0;border:0"><img class="avatar" src="${esc(s.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(s.display_name||s.official_name)}&background=b91c1c&color=fff`)}"><div class="grow"><b>${esc(s.display_name||s.official_name)}</b><div class="muted">${esc(s.student_code||'')} • B4</div></div><span class="badge">Student</span></div><p class="muted" style="font-size:11px">${esc(s.official_name)}</p></div>`).join('')}</div>`}
function subjectsV(){return title(t('subjects'),'Telecommunication curriculum and class progress.')+`<div class="grid c3">${S.subjects.map(s=>`<div class="card"><div class="head"><h3>${esc(s.name)}</h3><span class="badge">${s.progress||0}%</span></div><p class="muted">${esc(s.teacher_name||'')}</p><div class="barline"><span style="width:${s.progress||0}%"></span></div><button class="btn ghost" style="margin-top:13px" onclick="go('resources')">Open resources →</button></div>`).join('')||'<div class="card empty">No subjects configured yet.</div>'}</div>`}
function scheduleV(){return title(t('schedule'),'Official B4 schedule. The admin can update it later.')+`<div class="card tablewrap"><table class="table"><thead><tr><th>DAY</th><th>PERIOD 1</th><th>PERIOD 2</th><th>PERIOD 3</th><th>PERIOD 4</th></tr></thead><tbody>${S.schedule.map(r=>`<tr><td><b>${esc(r.day_name)}</b></td><td><div class="classblock">${esc(r.p1||'—')}</div></td><td><div class="classblock">${esc(r.p2||'—')}</div></td><td><div class="classblock">${esc(r.p3||'—')}</div></td><td><div class="classblock">${esc(r.p4||'—')}</div></td></tr>`).join('')||`<tr><td colspan="5" class="empty">Schedule will be added by the admin.</td></tr>`}</tbody></table></div>`}
function tasksV(){return title(t('tasks'),'Assignments from the real backend.',can('MANAGE_ASSIGNMENTS')?`<button class="btn primary" onclick="assignmentModal()">＋ ${t('add')}</button>`:'')+`<div class="grid c2">${S.tasks.map(x=>`<div class="card"><div class="head"><h3>${esc(x.title)}</h3><span class="badge ${x.status==='DONE'?'good':'warn'}">${esc(x.status||'OPEN')}</span></div><p class="muted">${esc(x.subject_name||'')}</p><div class="meter"><span>Due</span><b>${esc(x.due_at||'—')}</b></div>${x.description?`<p>${esc(x.description)}</p>`:''}</div>`).join('')||'<div class="card empty">No assignments yet.</div>'}</div>`}
function resourcesV(){return title(t('resources'),S.lang==='ar'?'مصادر الدراسة والملفات المشتركة.':'Shared lessons, files and study links.')+`<div class="grid c3">${S.resources.map(r=>`<article class="card"><div class="head"><span class="badge">${esc(r.resource_type||'RESOURCE')}</span><span class="muted">${esc(r.subject_name||'B4')}</span></div><h3>${esc(r.title)}</h3><p class="muted">${esc(r.description||'')}</p>${r.url?`<a class="btn primary" href="${esc(r.url)}" target="_blank" rel="noopener">Open resource →</a>`:r.file_url?`<a class="btn primary" href="${esc(r.file_url)}" target="_blank" rel="noopener">Open file →</a>`:''}</article>`).join('')||'<div class="card empty">No resources have been published yet.</div>'}</div>`}
function examsV(){return title(t('exams'),S.lang==='ar'?'الامتحانات المنشورة من الإدارة والمدرسين.':'Published exams and exam schedules.')+`<div class="grid c2">${S.exams.map(e=>`<article class="card"><div class="head"><span class="badge ${e.status==='OPEN'?'good':e.status==='CLOSED'?'red':'warn'}">${esc(e.status)}</span><span class="muted">${esc(e.subject_name||'')}</span></div><h3>${esc(e.title)}</h3><p class="muted">${esc(e.description||'')}</p><div class="meter"><span>Starts</span><b>${esc(e.starts_at||'Not scheduled')}</b></div><div class="meter"><span>Duration</span><b>${e.duration_minutes?esc(e.duration_minutes)+' min':'—'}</b></div></article>`).join('')||'<div class="card empty">No exams have been published yet.</div>'}</div><div class="card" style="margin-top:15px"><h3>Practice with B4 AI</h3><p class="muted">Use the assistant for explanations and revision before an exam.</p><button class="btn primary" onclick="aiModal()">✦ Ask B4 AI</button></div>`}
function newsV(){return title(t('news'),'Official class announcements.',can('MANAGE_ANNOUNCEMENTS')?`<button class="btn primary" onclick="announcementModal()">＋ ${t('add')}</button>`:'')+`<div class="grid">${S.announcements.map(a=>`<div class="card"><div class="head"><span class="badge">${esc(a.category||'General')}</span><span class="muted">${esc(a.created_at||'')}</span></div><h3>${esc(a.title)}</h3><p class="muted">${esc(a.body)}</p></div>`).join('')||'<div class="card empty">No announcements yet.</div>'}</div>`}
function chatV(){return title(t('chat'),S.lang==='ar'?'اضغط مطولاً على رسالتك للتعديل أو الحذف.':'Long-press your message to edit or delete.')+`<div class="card chat"><div class="messages" id="messages">${S.messages.map(m=>{const mine=S.me&&m.user_id===S.me.id;const edited=m.edited_at?' <span class="edited">Edited</span>':'';return `<div class="msg ${mine?'me':''}" data-message-id="${m.id}" oncontextmenu="messageMenu(event,${m.id})" ontouchstart="startMessagePress(event,${m.id})" ontouchend="endMessagePress()" ontouchcancel="cancelMessagePress()"><img class="avatar" src="${esc(m.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(m.display_name||'User')}&background=b91c1c&color=fff`)}"><div><b style="font-size:10px">${esc(m.display_name)}</b><div class="bubble">${esc(m.body)}</div><small class="muted">${esc(m.created_at||'')}${edited}</small></div></div>`}).join('')||'<div class="empty">No messages yet.</div>'}</div><form class="chatform" onsubmit="send(event)"><input id="chatInput" placeholder="${S.lang==='ar'?'اكتب رسالة...':'Write a message...'}" ${S.me?'':'disabled'}><button class="btn primary" ${S.me?'':'disabled'}>➤</button></form></div>`}
function attendanceRate(){if(!S.attendance.length)return 0;const p=S.attendance.filter(x=>x.status==='PRESENT').length;return Math.round(p/S.attendance.length*100)}
function attendanceV(){return title(t('attendance'),'Present, absent, late and excused records.')+`<div class="grid c2"><div class="card"><h2>${attendanceRate()}%</h2><p class="muted">Present rate</p><div class="barline"><span style="width:${attendanceRate()}%"></span></div></div><div class="card"><div class="list">${S.attendance.slice(0,12).map(a=>`<div class="item"><b class="grow">${esc(a.date)}</b><span class="badge ${a.status==='PRESENT'?'good':a.status==='ABSENT'?'red':'warn'}">${esc(a.status)}</span></div>`).join('')||'<div class="empty">No attendance records yet.</div>'}</div></div></div>`}
function adminV(){
  if(!can('ADMIN_CENTER'))return '';
  const cards=[];
  if(can('MANAGE_ADMINS')||can('MANAGE_ROLES'))cards.push('<div class="card"><div class="ico">⚙</div><h3>People & Permissions</h3><p class="muted">Give each account its own role and permissions.</p><button class="btn ghost" onclick="permissionsModal()">Manage →</button></div>');
  if(can('MANAGE_STUDENTS'))cards.push('<div class="card"><div class="ico">♙</div><h3>Students</h3><p class="muted">Manage official B4 students.</p><button class="btn ghost" onclick="adminStudentModal()">Manage →</button></div>');
  if(can('MANAGE_KEYS'))cards.push('<div class="card"><div class="ico">🔑</div><h3>Activation Keys</h3><p class="muted">Create one-time account keys.</p><button class="btn ghost" onclick="activationModal(true)">Manage →</button></div>');
  if(can('MANAGE_ASSIGNMENTS'))cards.push('<div class="card"><div class="ico">✓</div><h3>Assignments</h3><p class="muted">Publish class assignments.</p><button class="btn ghost" onclick="assignmentModal()">Create →</button></div>');
  if(can('MANAGE_ANNOUNCEMENTS'))cards.push('<div class="card"><div class="ico">◈</div><h3>Announcements</h3><p class="muted">Publish official notices.</p><button class="btn ghost" onclick="announcementModal()">Create →</button></div>');
  if(can('VIEW_LOGS'))cards.push('<div class="card"><div class="ico">⌁</div><h3>Logs</h3><p class="muted">Review chat edit history.</p><button class="btn ghost" onclick="logsModal()">View →</button></div>');
  return title(t('admin'),S.lang==='ar'?'إدارة بيانات الفصل والصلاحيات والمحتوى.':'Manage class data, content, accounts and security.')+`<div class="grid c3">${cards.join('')}</div>`;
}
function settingsV(){return title(t('settings'),'Personal preferences and account security.')+`<div class="grid c2"><div class="card"><h3>${t('account')}</h3><div class="form"><div class="field"><label>${t('display')}</label><input id="displayName" value="${esc(S.me?.display_name||'')}" ${S.me?'':'disabled'}></div><button class="btn primary" onclick="saveProfile()" ${S.me?'':'disabled'}>${t('save')}</button><button class="btn ghost" onclick="passwordModal()" ${S.me?'':'disabled'}>Change password</button></div></div><div class="card"><h3>Preferences</h3><div class="list"><button class="item quick" onclick="toggleTheme()"><span class="grow">Appearance</span><b>${S.theme}</b></button><button class="item quick" onclick="toggleLang()"><span class="grow">Language</span><b>${S.lang}</b></button><button class="item quick" onclick="installApp()"><span class="grow">${t('install')}</span>→</button></div></div><div class="card"><h3>${t('linked')}</h3><p class="muted">Google, Discord and Facebook can be linked only to an existing B4 account. They never create a new B4 account.</p><div class="list"><div class="item"><span class="grow">Google</span><span class="badge">Not linked</span></div><div class="item"><span class="grow">Discord</span><span class="badge">Not linked</span></div><div class="item"><span class="grow">Facebook</span><span class="badge">Not linked</span></div></div></div><div class="card"><h3>Session</h3><p class="muted">Persistent secure cookie session. Logging out ends the session.</p><button class="btn danger" onclick="logout()">${t('logout')}</button></div></div>`}
function notificationsV(){return title('Notifications',S.lang==='ar'?'تنبيهات الحساب والفصل.':'Account and class notifications.')+`<div class="grid">${S.notifications.map(n=>`<div class="card ${n.read_at?'':'notice'}"><div class="head"><h3>${esc(n.title)}</h3><small class="muted">${esc(n.created_at||'')}</small></div><p class="muted">${esc(n.body||'')}</p></div>`).join('')||'<div class="card empty">No notifications yet.</div>'}</div>`}
function loginModal(){modal(`<div class="modalhead"><h2>${t('login')}</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="login(event)"><div class="field"><label>Display name / Login</label><input id="loginName" required autocomplete="username"></div><div class="field"><label>${t('password')}</label><input id="loginPassword" type="password" required autocomplete="current-password"></div><button class="btn primary">${t('login')} →</button></form><div class="notice" style="margin-top:14px">New account? Use your one-time Activation Key first.</div><button class="btn ghost" style="margin-top:10px" onclick="activationUserModal()">${t('activate')}</button>`)}
async function login(e){e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({login:$('#loginName').value.trim(),password:$('#loginPassword').value})});close();await loadMe();toast('Login successful ✓')}catch(x){toast(x.message)}}
function activationUserModal(){modal(`<div class="modalhead"><h2>${t('activate')}</h2><button class="close" onclick="close()">×</button></div><p class="muted">Your activation key is one-time and is already linked to your B4 identity.</p><form class="form" onsubmit="activate(event)"><div class="field"><label>One-time key</label><input id="activationKey" required autocomplete="off" spellcheck="false"></div><div class="field"><label>${t('display')}</label><input id="activationDisplay" required maxlength="120"></div><div class="field"><label>${t('password')}</label><input id="activationPassword" type="password" minlength="8" required autocomplete="new-password"></div><button class="btn primary">Create B4 account →</button></form>`)}
async function activate(e){e.preventDefault();try{const d=await api('/api/auth/activate',{method:'POST',body:JSON.stringify({key:$('#activationKey').value.trim(),displayName:$('#activationDisplay').value.trim(),password:$('#activationPassword').value})});close();toast(d.message||'Account created ✓');loginModal()}catch(x){toast(x.message)}}
function passwordModal(){modal(`<div class="modalhead"><h2>Change password</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="changePassword(event)"><div class="field"><label>Current password</label><input id="oldPw" type="password" required></div><div class="field"><label>New password</label><input id="newPw" type="password" minlength="8" required></div><button class="btn primary">Save password</button></form>`)}
async function changePassword(e){e.preventDefault();try{await api('/api/auth/password',{method:'POST',body:JSON.stringify({currentPassword:$('#oldPw').value,newPassword:$('#newPw').value})});close();toast('Password changed ✓')}catch(x){toast(x.message)}}
async function saveProfile(){try{await api('/api/auth/profile',{method:'PATCH',body:JSON.stringify({displayName:$('#displayName').value.trim()})});await loadMe();toast('Profile saved ✓')}catch(x){toast(x.message)}}
async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>{});S.me=null;render();toast('Logged out')}function accountInfo(){modal(`<div class="modalhead"><h2>Account security</h2><button class="close" onclick="close()">×</button></div><p class="muted">Passwords are stored as secure hashes. Super Admin cannot view original passwords.</p><div class="notice">Use Reset Password / temporary password workflows instead of exposing passwords.</div>`)}
async function activationModal(manage=false){if(!S.me||S.me.role!=='SUPER_ADMIN'){toast('Super Admin only');return}let keys=[],people={students:[],teachers:[]};try{[keys,people]=[(await api('/api/admin/activation-keys')).keys||[],await api('/api/admin/people')]}catch(e){toast(e.message);return}const opts=[...people.students.map(p=>`<option value="STUDENT:${p.id}">Student • ${esc(p.display_name)} (${esc(p.student_code)})</option>`),...people.teachers.map(p=>`<option value="TEACHER:${p.id}">Teacher • ${esc(p.display_name)}</option>`)].join('');modal(`<div class="modalhead"><h2>Activation Keys</h2><button class="close" onclick="close()">×</button></div><p class="muted">Generate a key only for a person who does not already have a B4 account.</p><form class="form" onsubmit="createKey(event)"><div class="field"><label>Person</label><select id="keyPerson" required>${opts}</select></div><button class="btn primary">Generate one-time key</button></form><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="list">${keys.map(k=>`<div class="item"><span class="grow"><b>${esc(k.key_preview)}</b><br><small class="muted">${esc(k.person_name||'')} • ${esc(k.status)}</small></span><span class="badge">Hash only</span></div>`).join('')||'<div class="empty">No active keys.</div>'}</div>`)}
async function createKey(e){e.preventDefault();try{const [personType,personId]=$('#keyPerson').value.split(':');const d=await api('/api/admin/activation-keys',{method:'POST',body:JSON.stringify({personType,personId:Number(personId)})});await navigator.clipboard?.writeText(d.key);modal('<div class="modalhead"><h2>Activation key created</h2><button class="close" onclick="close()">×</button></div><p class="muted">Copy this key now. The full key is intentionally not stored for later viewing.</p><div class="notice" style="font-family:monospace;font-size:16px;word-break:break-all">'+esc(d.key)+'</div><button class="btn primary" style="margin-top:14px" onclick="copyText(\''+esc(d.key)+'\')">Copy key</button>');toast('Key generated ✓')}catch(x){toast(x.message)}}async function copyText(v){try{await navigator.clipboard.writeText(v)}catch{}toast(v)}function adminStudentModal(){modal('<div class="modalhead"><h2>Add student</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="createStudent(event)"><div class="field"><label>Student Code</label><input id="newStudentCode" placeholder="B4-25" required></div><div class="field"><label>Official full name</label><input id="newOfficialName" required></div><div class="field"><label>Display name</label><input id="newDisplayName" required></div><button class="btn primary">Add student →</button></form>')}
async function createStudent(e){e.preventDefault();try{await api('/api/admin/students',{method:'POST',body:JSON.stringify({studentCode:$('#newStudentCode').value,officialName:$('#newOfficialName').value,displayName:$('#newDisplayName').value})});close();await loadData();render();toast('Student added ✓')}catch(x){toast(x.message)}}
function assignmentModal(){modal('<div class="modalhead"><h2>Create assignment</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="createAssignment(event)"><div class="field"><label>Title</label><input id="assignmentTitle" required></div><div class="field"><label>Subject</label><select id="assignmentSubject">'+S.subjects.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join('')+'</select></div><div class="field"><label>Description</label><textarea id="assignmentDescription" rows="4"></textarea></div><div class="field"><label>Due date</label><input id="assignmentDue" type="datetime-local"></div><button class="btn primary">Publish assignment →</button></form>')}
async function createAssignment(e){e.preventDefault();try{await api('/api/admin/assignments',{method:'POST',body:JSON.stringify({title:$('#assignmentTitle').value,description:$('#assignmentDescription').value,subjectId:Number($('#assignmentSubject').value)||null,dueAt:$('#assignmentDue').value||null})});close();await loadData();render();toast('Assignment published ✓')}catch(x){toast(x.message)}}
function announcementModal(){modal('<div class="modalhead"><h2>New announcement</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="createAnnouncement(event)"><div class="field"><label>Title</label><input id="announcementTitle" required></div><div class="field"><label>Category</label><input id="announcementCategory" value="General"></div><div class="field"><label>Message</label><textarea id="announcementBody" rows="6" required></textarea></div><button class="btn primary">Publish announcement →</button></form>')}
async function createAnnouncement(e){e.preventDefault();try{await api('/api/admin/announcements',{method:'POST',body:JSON.stringify({title:$('#announcementTitle').value,body:$('#announcementBody').value,category:$('#announcementCategory').value})});close();await loadData();render();toast('Announcement published ✓')}catch(x){toast(x.message)}}async function logsModal(){try{const d=await api('/api/admin/chat/edit-logs');modal('<div class="modalhead"><h2>Chat Edit Logs</h2><button class="close" onclick="close()">×</button></div><div class="list">'+((d.logs||[]).map(x=>'<div class="item" style="display:block"><b>'+esc(x.editor_name||'Unknown')+'</b><small class="muted"> • '+esc(x.created_at||'')+'</small><div class="muted" style="margin-top:7px">Old: '+esc(x.old_body)+'</div><div style="margin-top:4px">New: '+esc(x.new_body)+'</div></div>').join('')||'<div class="empty">No edit logs yet.</div>')+'</div>')}catch(x){toast(x.message)}}
let messagePressTimer=null;
function startMessagePress(e,id){cancelMessagePress();messagePressTimer=setTimeout(()=>messageMenu(e,id),550)}
function endMessagePress(){clearTimeout(messagePressTimer);messagePressTimer=null}
function cancelMessagePress(){clearTimeout(messagePressTimer);messagePressTimer=null}
function messageMenu(e,id){if(e){e.preventDefault();e.stopPropagation()}const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m||!S.me)return;const mine=Number(m.user_id)===Number(S.me.id);const canDelete=mine||can('MANAGE_CHAT');if(!mine&&!canDelete)return;const buttons=(mine?'<button class="item quick" onclick="close();editMessage('+id+')">✎ <span class="grow">Edit</span>→</button>':'')+'<button class="item quick" onclick="close();deleteMessage('+id+')">⌫ <span class="grow">Delete</span>→</button>';modal('<div class="modalhead"><h2>'+(S.lang==='ar'?'إدارة الرسالة':'Message actions')+'</h2><button class="close" onclick="close()">×</button></div><div class="list">'+buttons+'</div>')}
function editMessage(id){const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m||!S.me||Number(m.user_id)!==Number(S.me.id))return;modal('<div class="modalhead"><h2>'+(S.lang==='ar'?'تعديل الرسالة':'Edit message')+'</h2><button class="close" onclick="close()">×</button></div><form class="form" onsubmit="saveEdit(event,'+id+')"><div class="field"><label>'+(S.lang==='ar'?'الرسالة':'Message')+'</label><textarea id="editMessageBody" rows="4" maxlength="4000" required>'+esc(m.body)+'</textarea></div><button class="btn primary">'+(S.lang==='ar'?'حفظ التعديل':'Save edit')+' →</button></form>');setTimeout(()=>$('#editMessageBody')?.focus(),50)}
async function saveEdit(e,id){e.preventDefault();const body=$('#editMessageBody')?.value.trim();if(!body)return;try{const d=await api('/api/chat/messages/'+id,{method:'PATCH',body:JSON.stringify({body})});const i=S.messages.findIndex(x=>Number(x.id)===Number(id));if(i>=0)S.messages[i]=d.message;close();render();toast(S.lang==='ar'?'تم تعديل الرسالة ✓':'Message edited ✓')}catch(x){toast(x.message)}}
async function deleteMessage(id){try{await api('/api/chat/messages/'+id,{method:'DELETE'});S.messages=S.messages.filter(x=>Number(x.id)!==Number(id));close();render();toast(S.lang==='ar'?'تم حذف الرسالة ✓':'Message deleted ✓')}catch(x){toast(x.message)}}
async function send(e){e.preventDefault();const v=$('#chatInput')?.value.trim();if(!v||!S.me)return;try{const d=await api('/api/chat/messages',{method:'POST',body:JSON.stringify({body:v})});S.messages.push(d.message);$('#chatInput').value='';render();}catch(x){toast(x.message)}}
function aiModal(){modal(`<div class="modalhead"><h2>✦ ${t('ai')}</h2><button class="close" onclick="close()">×</button></div><p class="muted">${S.lang==='ar'?'مساعد خاص بفصل B4، والـAPI Key يظل على الـBackend.':'B4-specific assistant. The OpenAI key stays on the backend.'}</p><div class="field"><label>Question</label><textarea id="aiq" rows="5" placeholder="${S.lang==='ar'?'مثلاً: اشرح TDM بطريقة بسيطة':'Example: Explain TDM simply'}"></textarea></div><button class="btn primary" onclick="answerAI()">Ask AI →</button><div id="air" style="margin-top:14px"></div>`)}
async function answerAI(){if(!can('USE_AI'))return;const q=$('#aiq')?.value.trim();if(!q)return toast('Write a question first');const r=$('#air');r.innerHTML='<div class="card">Thinking…</div>';try{const d=await api('/api/ai',{method:'POST',body:JSON.stringify({message:q})});r.innerHTML=`<div class="card"><b>✦ B4 AI</b><p style="white-space:pre-wrap">${esc(d.answer)}</p></div>`}catch(x){r.innerHTML=`<div class="card notice">${esc(x.message)}</div>`}}
async function permissionsModal(){
  if(!can('MANAGE_ROLES')&&!can('MANAGE_ADMINS'))return;
  try{const [pd,ud]=await Promise.all([api('/api/admin/permissions'),api('/api/admin/users')]);window.__permissionDefs=pd.permissions||[];window.__permissionUsers=ud.users||[];const opts=window.__permissionUsers.map(u=>`<option value="${u.id}">${esc(u.display_name)} • ${esc(u.role)}</option>`).join('');modal(`<div class="modalhead"><h2>People & Permissions</h2><button class="close" onclick="close()">×</button></div><div class="field"><label>Account</label><select id="permUser" onchange="renderPermissionEditor()">${opts}</select></div><div id="permEditor" style="margin-top:14px"></div>`);renderPermissionEditor();}catch(e){toast(e.message)}
}
function renderPermissionEditor(){
  const u=window.__permissionUsers?.find(x=>Number(x.id)===Number($('#permUser')?.value));if(!u)return;const superAdmin=u.role==='SUPER_ADMIN',direct=new Set(u.direct_permissions||[]);
  const roleEditor=can('MANAGE_ADMINS')&&!superAdmin?`<div class="field"><label>Role</label><select id="permRole"><option value="STUDENT" ${u.role==='STUDENT'?'selected':''}>STUDENT</option><option value="TEACHER" ${u.role==='TEACHER'?'selected':''}>TEACHER</option><option value="ADMIN" ${u.role==='ADMIN'?'selected':''}>ADMIN</option></select></div>`:'';
  const boxes=(window.__permissionDefs||[]).map(p=>`<label class="item" style="cursor:pointer"><input type="checkbox" data-perm="${esc(p.code)}" ${direct.has(p.code)||superAdmin?'checked':''} ${superAdmin?'disabled':''}> <span class="grow"><b>${esc(p.label)}</b><small class="muted">${esc(p.code)}</small></span></label>`).join('');
  $('#permEditor').innerHTML=roleEditor+`<div class="notice">Role: <b>${esc(u.role)}</b> • SUPER_ADMIN always has every permission.</div><div class="list" style="max-height:360px;overflow:auto;margin-top:12px">${boxes}</div>${superAdmin?'':'<button class="btn primary" style="margin-top:14px" onclick="savePermissions()">Save changes</button>'}`;
}
async function savePermissions(){
  const id=Number($('#permUser')?.value),codes=[...document.querySelectorAll('[data-perm]:checked')].map(x=>x.dataset.perm);
  try{if($('#permRole')?.value)await api('/api/admin/users/'+id+'/role',{method:'PATCH',body:JSON.stringify({role:$('#permRole').value})});await api('/api/admin/users/'+id+'/permissions',{method:'PUT',body:JSON.stringify({permissionCodes:codes})});toast('Permissions saved ✓');const d=await api('/api/admin/users');window.__permissionUsers=d.users||[];renderPermissionEditor();}catch(e){toast(e.message)}
}
function themes(){modal(`<div class="modalhead"><h2>Theme Studio</h2><button class="close" onclick="close()">×</button></div><div class="grid c3">${['#7c3aed','#6d28d9','#8b5cf6','#a855f7','#9333ea','#c084fc'].map(c=>`<button class="btn" style="height:65px;background:${c};color:white" onclick="accent('${c}')">${c}</button>`).join('')}</div>`)}function accent(c){document.documentElement.style.setProperty('--p',c);document.documentElement.style.setProperty('--p2',c);localStorage.b4Accent=c;toast('Theme updated ✓')}
function commandCenter(){modal(`<div class="modalhead"><h2>Quick navigation</h2><button class="close" onclick="close()">×</button></div><input id="cmd" placeholder="Search pages..." oninput="filterCommands()"><div id="cmdList" class="list" style="margin-top:12px">${nav.filter(x=>x[0]!=='g').map(x=>`<button class="item quick cmditem" onclick="close();go('${x[0]}')">${x[1]} <span class="grow">${t(x[2])}</span>→</button>`).join('')}</div>`)}function filterCommands(){const q=($('#cmd')?.value||'').toLowerCase();document.querySelectorAll('.cmditem').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')}
function toggleTheme(){S.theme=S.theme==='dark'?'light':'dark';localStorage.b4Theme=S.theme;render()}function toggleLang(){S.lang=S.lang==='en'?'ar':'en';localStorage.b4Lang=S.lang;render()}function installApp(){if(window.__install){window.__install.prompt();window.__install=null}else toast(S.lang==='ar'?'استخدم قائمة المتصفح لتثبيت التطبيق':'Use the browser menu to install the app')}
const views={dashboard,students:studentsV,subjects:subjectsV,schedule:scheduleV,assignments:tasksV,resources:resourcesV,exams:examsV,announcements:newsV,chat:chatV,attendance:attendanceV,admin:adminV,settings:settingsV,notifications:notificationsV};
async function loadMe(){try{const d=await api('/api/auth/me');S.me=d.user;S.online=true}catch{S.me=null;S.online=false}await loadData();render()}
async function loadData(){try{const d=await api('/api/bootstrap');S.students=d.students||[];S.subjects=d.subjects||[];S.tasks=d.assignments||[];S.announcements=d.announcements||[];S.schedule=d.schedule||[];S.resources=d.resources||[];S.exams=d.exams||[];S.attendance=d.attendance||[];S.messages=d.messages||[];S.notifications=d.notifications||[];S.dataError=''}catch(e){S.dataError=e.message||'Could not load class data';S.students=[];S.subjects=[];S.tasks=[];S.announcements=[];S.schedule=[];S.resources=[];S.exams=[];S.notifications=[];S.attendance=[];S.messages=[]}}
function render(){
  document.documentElement.dir=S.lang==='ar'?'rtl':'ltr';document.documentElement.lang=S.lang;document.body.classList.toggle('ar',S.lang==='ar');document.body.classList.toggle('dark',S.theme==='dark');
  const publicViews=['dashboard','students','subjects','schedule','assignments','resources','exams','announcements','chat','attendance'];
  if(!can(S.view==='admin'?'ADMIN_CENTER':S.view==='settings'?'ACCOUNT':publicViews.includes(S.view)?'VIEW_CLASS':null))S.view='dashboard';
  $('#nav').innerHTML=buildNav();$('#theme span').textContent=S.theme==='dark'?t('themeL'):t('themeD');$('#lang span').textContent=S.lang==='en'?'العربية':'English';$('#search').placeholder=t('search');$('#topName').textContent=S.me?.display_name||'Guest';
  if($('#ai'))$('#ai').style.display=can('USE_AI')?'':'none';
  $('#content').innerHTML=`<div class="page">${views[S.view]()}</div>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>go(b.dataset.v));
}
$('#theme').onclick=toggleTheme;$('#lang').onclick=toggleLang;$('#mobile').onclick=()=>$('#side').classList.toggle('open');$('#bell').onclick=()=>toast(S.lang==='ar'?'الإشعارات سيتم ربطها بالـBackend':'Notifications will be connected to the backend');$('#ai').onclick=aiModal;$('#profile').onclick=()=>S.me?go('settings'):loginModal();$('#back').onclick=e=>{if(e.target.id==='back')close()};$('#install').onclick=installApp;$('#search').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;const x=[...document.querySelectorAll('.card,.item')].find(a=>a.textContent.toLowerCase().includes(q));if(x){x.scrollIntoView({behavior:'smooth',block:'center'});x.animate([{transform:'scale(1)'},{transform:'scale(1.02)'},{transform:'scale(1)'}],{duration:450})}};document.addEventListener('mousemove',e=>{const g=$('#glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});let promptInstall;addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptInstall=e;window.__install=e});const ac=localStorage.b4Accent;if(ac)accent(ac);if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
(async()=>{await loadMe();const loader=$('#loader');if(loader)setTimeout(()=>loader.classList.add('hide'),500)})();


/* B4 v2 UX + access-control enhancements */
window.close=function(){const b=document.querySelector('#back');if(b)b.classList.remove('show')};
function closeModalSafe(){window.close()}
function buildNav(){
  const items=S.me?[
    ['dashboard','⌂','dash'],['students','♙','students'],['subjects','▣','subjects'],['schedule','◫','schedule'],
    ['assignments','✓','tasks'],['resources','▤','resources'],['exams','⌁','exams'],['announcements','◈','news'],['chat','◌','chat'],['attendance','◉','attendance'],
    ...(can('ADMIN_CENTER')?[['admin','⚙','admin']]:[]),['settings','⚙','settings']
  ]:[['students','♙','students'],['subjects','▣','subjects'],['schedule','◫','schedule']];
  return items.filter(x=>S.me||['students','subjects','schedule'].includes(x[0])).filter(x=>S.me||true).map(x=>
    '<button data-v="'+x[0]+'" class="'+(S.view===x[0]?'active':'')+'">'+x[1]+' <span>'+t(x[2])+'</span>'+(x[0]==='assignments'&&S.tasks.length?'<em>'+S.tasks.length+'</em>':'')+'</button>'
  ).join('');
}
function render(){
  document.documentElement.dir=S.lang==='ar'?'rtl':'ltr';document.documentElement.lang=S.lang;document.body.classList.toggle('ar',S.lang==='ar');document.body.classList.toggle('dark',S.theme==='dark');
  if(!S.me&&!['students','subjects','schedule'].includes(S.view))S.view='students';
  if(S.me&&S.view==='admin'&&!can('ADMIN_CENTER'))S.view='dashboard';
  if(S.me&&S.view==='settings'&&!can('ACCOUNT'))S.view='dashboard';
  $('#nav').innerHTML=buildNav();$('#theme span').textContent=S.theme==='dark'?t('themeL'):t('themeD');$('#lang span').textContent=S.lang==='en'?'العربية':'English';$('#search').placeholder=t('search');$('#topName').textContent=S.me?.display_name||'Guest';
  if($('#ai'))$('#ai').style.display=can('USE_AI')?'':'none';
  $('#content').innerHTML='<div class="page">'+views[S.view]()+'</div>';document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>go(b.dataset.v));
}
async function loadMe(){
  try{const d=await api('/api/auth/me');S.me=d.user;S.online=true;const l=await api('/api/auth/linked').catch(()=>({linked:[]}));S.linked=l.linked||[];}
  catch{S.me=null;S.online=false;S.linked=[];}
  await loadData();render();
  const gp=new URLSearchParams(location.search).get('google');
  if(gp){history.replaceState({},'',location.pathname);toast(gp==='linked'?'Google account linked ✓':gp==='already-linked'?'This Google account is already linked to another B4 account':gp==='cancelled'?'Google linking cancelled':'Google linking failed');}
}
function linkedGoogle(){location.href=API_BASE+'/api/auth/google/start'}
function settingsV(){
  const google= S.linked.find(x=>x.provider==='GOOGLE');
  return title(t('settings'),'Personal preferences and account security.')+
  '<div class="grid c2">'+
  '<div class="card"><h3>'+t('account')+'</h3><div class="form"><div class="field"><label>'+t('display')+'</label><input id="displayName" value="'+esc(S.me?.display_name||'')+'"></div><button class="btn primary" onclick="saveProfile()">'+t('save')+'</button><button class="btn ghost" onclick="passwordModal()">Change password</button></div></div>'+
  '<div class="card"><h3>Preferences</h3><div class="list"><button class="item quick" onclick="toggleTheme()"><span class="grow">Appearance</span><b>'+S.theme+'</b></button><button class="item quick" onclick="toggleLang()"><span class="grow">Language</span><b>'+S.lang+'</b></button><button class="item quick" onclick="installApp()"><span class="grow">'+t('install')+'</span>→</button></div></div>'+
  '<div class="card"><h3>'+t('linked')+'</h3><p class="muted">Link Google to your existing B4 account. Google linking never creates a new B4 account.</p><div class="list"><div class="item"><span class="grow">Google</span>'+(google?'<span class="badge good">Linked</span>':'<button class="btn primary" onclick="linkedGoogle()">Link Google</button>')+'</div><div class="item"><span class="grow">Discord</span><span class="badge">Not Available</span></div><div class="item"><span class="grow">Facebook</span><span class="badge">Not Available</span></div></div></div>'+ 
  '<div class="card"><h3>Session</h3><p class="muted">Persistent secure cookie session. Logging out ends the session.</p><button class="btn danger" onclick="logout()">'+t('logout')+'</button></div></div>';
}
function resourceModal(){
  if(!can('MANAGE_RESOURCES'))return;
  modal('<div class="modalhead"><h2>Study Resources</h2><button class="close" onclick="window.close()">×</button></div><div class="grid c2"><form class="form" onsubmit="createResource(event)"><h3>Add link / note</h3><div class="field"><label>Title</label><input id="resTitle" required></div><div class="field"><label>Subject</label><select id="resSubject">'+S.subjects.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></div><div class="field"><label>URL</label><input id="resUrl" type="url" placeholder="https://..."></div><div class="field"><label>Description</label><textarea id="resDesc" rows="3"></textarea></div><button class="btn primary">Publish resource</button></form><form class="form" onsubmit="uploadPdf(event)"><h3>Upload PDF</h3><div class="field"><label>Title</label><input id="pdfTitle"></div><div class="field"><label>Subject</label><select id="pdfSubject">'+S.subjects.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></div><div class="field"><label>PDF file • max 15 MB</label><input id="pdfFile" type="file" accept="application/pdf" required></div><div class="field"><label>Description</label><textarea id="pdfDesc" rows="3"></textarea></div><button class="btn primary">Upload PDF →</button></form></div>');
}
async function createResource(e){e.preventDefault();try{await api('/api/admin/resources',{method:'POST',body:JSON.stringify({title:$('#resTitle').value,description:$('#resDesc').value,url:$('#resUrl').value,subjectId:Number($('#resSubject').value)||null})});window.close();await loadData();render();toast('Resource published ✓')}catch(x){toast(x.message)}}
async function uploadPdf(e){e.preventDefault();const file=$('#pdfFile').files[0];if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('title',$('#pdfTitle').value||file.name);fd.append('description',$('#pdfDesc').value);fd.append('subjectId',$('#pdfSubject').value);try{const r=await fetch(API_BASE+'/api/admin/resources/pdf',{method:'POST',credentials:'include',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Upload failed');window.close();await loadData();render();toast('PDF uploaded ✓')}catch(x){toast(x.message)}}
window.__examQuestions=[];
function examModal(){if(!can('MANAGE_EXAMS'))return;window.__examQuestions=[];addExamQuestion();modal('<div class="modalhead"><h2>Create Exam</h2><button class="close" onclick="window.close()">×</button></div><form class="form" onsubmit="createExam(event)"><div class="field"><label>Title</label><input id="examTitle" required></div><div class="field"><label>Subject</label><select id="examSubject">'+S.subjects.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select></div><div class="grid c2"><div class="field"><label>Start</label><input id="examStart" type="datetime-local"></div><div class="field"><label>Deadline</label><input id="examEnd" type="datetime-local"></div></div><div class="field"><label>Time limit (minutes)</label><input id="examDuration" type="number" min="1" placeholder="e.g. 30"></div><div class="field"><label>Description</label><textarea id="examDesc" rows="3"></textarea></div><div class="head"><h3>Questions</h3><button type="button" class="btn ghost" onclick="addExamQuestion()">＋ Add question</button></div><div id="examQuestions"></div><button class="btn primary">Publish exam →</button></form>');renderExamQuestions();}
function addExamQuestion(){window.__examQuestions.push({type:'MCQ',text:'',options:['','','',''],correct:'',points:1});if($('#examQuestions'))renderExamQuestions()}
function renderExamQuestions(){const box=$('#examQuestions');if(!box)return;box.innerHTML=window.__examQuestions.map((q,i)=>'<div class="card" style="margin:10px 0"><div class="head"><b>Question '+(i+1)+'</b>'+(i?'<button type="button" class="btn danger" onclick="removeExamQuestion('+i+')">Remove</button>':'')+'</div><div class="field"><label>Question</label><textarea id="eq_text_'+i+'" rows="2" required>'+esc(q.text)+'</textarea></div><div class="field"><label>Type</label><select id="eq_type_'+i+'" onchange="renderExamQuestions()"><option value="MCQ" '+(q.type==='MCQ'?'selected':'')+'>MCQ</option><option value="TRUE_FALSE" '+(q.type==='TRUE_FALSE'?'selected':'')+'>True / False</option><option value="SHORT" '+(q.type==='SHORT'?'selected':'')+'>Short answer</option></select></div>'+(q.type==='MCQ'?'<div class="grid c2">'+q.options.map((o,j)=>'<input id="eq_opt_'+i+'_'+j+'" placeholder="Option '+(j+1)+'" value="'+esc(o)+'">').join('')+'</div>':'')+'<div class="grid c2"><div class="field"><label>Correct answer</label><input id="eq_correct_'+i+'" value="'+esc(q.correct)+'" required></div><div class="field"><label>Points</label><input id="eq_points_'+i+'" type="number" min="0.5" step="0.5" value="'+q.points+'"></div></div></div>').join('');}
function removeExamQuestion(i){window.__examQuestions.splice(i,1);renderExamQuestions()}
function collectExamQuestions(){return window.__examQuestions.map((q,i)=>{q.text=$('#eq_text_'+i).value.trim();q.type=$('#eq_type_'+i).value;q.correct=$('#eq_correct_'+i).value.trim();q.points=Number($('#eq_points_'+i).value)||1;q.options=q.type==='MCQ'?[0,1,2,3].map(j=>$('#eq_opt_'+i+'_'+j)?.value.trim()).filter(Boolean):[];return {questionText:q.text,questionType:q.type,options:q.options,correctAnswer:q.correct,points:q.points}})}
async function createExam(e){e.preventDefault();try{const questions=collectExamQuestions();await api('/api/admin/exams',{method:'POST',body:JSON.stringify({title:$('#examTitle').value,description:$('#examDesc').value,subjectId:Number($('#examSubject').value)||null,startsAt:$('#examStart').value||null,endsAt:$('#examEnd').value||null,durationMinutes:Number($('#examDuration').value)||null,questions})});window.close();await loadData();render();toast('Exam published ✓')}catch(x){toast(x.message)}}
function adminV(){if(!can('ADMIN_CENTER'))return '';const cards=[];if(can('MANAGE_ADMINS')||can('MANAGE_ROLES'))cards.push('<div class="card"><div class="ico">⚙</div><h3>People & Permissions</h3><p class="muted">Give each account its own role and permissions.</p><button class="btn ghost" onclick="permissionsModal()">Manage →</button></div>');if(can('MANAGE_STUDENTS'))cards.push('<div class="card"><div class="ico">♙</div><h3>Students</h3><p class="muted">Manage official B4 students.</p><button class="btn ghost" onclick="adminStudentModal()">Manage →</button></div>');if(can('MANAGE_KEYS'))cards.push('<div class="card"><div class="ico">🔑</div><h3>Activation Keys</h3><p class="muted">Create one-time account keys.</p><button class="btn ghost" onclick="activationModal(true)">Manage →</button></div>');if(can('MANAGE_ASSIGNMENTS'))cards.push('<div class="card"><div class="ico">✓</div><h3>Assignments</h3><p class="muted">Publish class assignments.</p><button class="btn ghost" onclick="assignmentModal()">Create →</button></div>');if(can('MANAGE_RESOURCES'))cards.push('<div class="card"><div class="ico">▤</div><h3>Resources & PDFs</h3><p class="muted">Publish study links, notes and PDF files.</p><button class="btn ghost" onclick="resourceModal()">Manage →</button></div>');if(can('MANAGE_EXAMS'))cards.push('<div class="card"><div class="ico">⌁</div><h3>Exam Center</h3><p class="muted">Create timed exams with a hard deadline.</p><button class="btn ghost" onclick="examModal()">Create →</button></div>');if(can('MANAGE_ANNOUNCEMENTS'))cards.push('<div class="card"><div class="ico">◈</div><h3>Announcements</h3><p class="muted">Publish official notices.</p><button class="btn ghost" onclick="announcementModal()">Create →</button></div>');if(can('VIEW_LOGS'))cards.push('<div class="card"><div class="ico">⌁</div><h3>Logs</h3><p class="muted">Review chat edit history.</p><button class="btn ghost" onclick="logsModal()">View →</button></div>');return title(t('admin'),'Manage class data, content, accounts and security.')+'<div class="grid c3">'+cards.join('')+'</div>';}
function messageClick(e,id){if(e){e.preventDefault();e.stopPropagation()}messageMenu(e,id)}
function messageMenu(e,id){if(e){e.preventDefault();e.stopPropagation()}const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m||!S.me)return;const mine=Number(m.user_id)===Number(S.me.id);const canDelete=mine||can('MANAGE_CHAT');const reply='<button class="item quick" onclick="window.close();replyToMessage('+id+')">↩ <span class="grow">Reply</span>→</button>';const edit=mine?'<button class="item quick" onclick="window.close();editMessage('+id+')">✎ <span class="grow">Edit</span>→</button>':'';const del=canDelete?'<button class="item quick" onclick="window.close();deleteMessage('+id+')">⌫ <span class="grow">Delete</span>→</button>':'';modal('<div class="modalhead"><h2>Message</h2><button class="close" onclick="window.close()">×</button></div><div class="list">'+reply+edit+del+'</div>')}
function replyToMessage(id){const m=S.messages.find(x=>Number(x.id)===Number(id));if(!m)return;S.replyTo=m;render();setTimeout(()=>$('#chatInput')?.focus(),50)}
function chatV(){return title(t('chat'),S.lang==='ar'?'اضغط على الرسالة لإظهار Reply أو التعديل أو الحذف.':'Click a message to Reply, edit or delete.')+'<div class="card chat"><div class="messages" id="messages">'+(S.messages.map(m=>{const mine=S.me&&Number(m.user_id)===Number(S.me.id);const edited=m.edited_at?' <span class="edited">Edited</span>':'';const rp=m.reply_to_id?'<div class="notice" style="margin-bottom:6px;font-size:11px">↩ '+esc(m.reply_display_name||'Message')+': '+esc(m.reply_body||'')+'</div>':'';return '<div class="msg '+(mine?'me':'')+'" data-message-id="'+m.id+'" onclick="messageClick(event,'+m.id+')" oncontextmenu="messageMenu(event,'+m.id+')" ontouchstart="startMessagePress(event,'+m.id+')" ontouchend="endMessagePress()" ontouchcancel="cancelMessagePress()"><img class="avatar" src="'+esc(m.avatar_url||('https://ui-avatars.com/api/?name='+encodeURIComponent(m.display_name||'User')+'&background=b91c1c&color=fff'))+'"><div><b style="font-size:10px">'+esc(m.display_name)+'</b><div class="bubble">'+rp+esc(m.body)+'</div><small class="muted">'+esc(m.created_at||'')+edited+'</small></div></div>'}).join('')||'<div class="empty">No messages yet.</div>')+'</div>'+(S.replyTo?'<div class="notice" style="margin-top:10px">↩ Replying to <b>'+esc(S.replyTo.display_name)+'</b><button class="btn ghost" style="float:right" onclick="S.replyTo=null;render()">Cancel</button><div class="muted">'+esc(S.replyTo.body)+'</div></div>':'')+'<form class="chatform" onsubmit="send(event)"><input id="chatInput" placeholder="'+(S.replyTo?'Reply to '+esc(S.replyTo.display_name):S.lang==='ar'?'اكتب رسالة...':'Write a message...')+'" '+(S.me?'':'disabled')+'><button class="btn primary" '+(S.me?'':'disabled')+'>➤</button></form></div>'}
async function send(e){e.preventDefault();const v=$('#chatInput')?.value.trim();if(!v||!S.me)return;try{const d=await api('/api/chat/messages',{method:'POST',body:JSON.stringify({body:v,replyToId:S.replyTo?.id||null})});S.messages.push(d.message);S.replyTo=null;$('#chatInput').value='';render()}catch(x){toast(x.message)}}
function examsV(){return title(t('exams'),S.lang==='ar'?'الامتحانات المنشورة.':'Published exams and exam schedules.')+'<div class="grid c2">'+(S.exams.map(e=>'<article class="card"><div class="head"><span class="badge '+(e.status==='OPEN'?'good':e.status==='CLOSED'?'red':'warn')+'">'+esc(e.status)+'</span><span class="muted">'+esc(e.subject_name||'')+'</span></div><h3>'+esc(e.title)+'</h3><p class="muted">'+esc(e.description||'')+'</p><div class="meter"><span>Starts</span><b>'+esc(e.starts_at||'Available now')+'</b></div><div class="meter"><span>Deadline</span><b>'+esc(e.ends_at||'No hard deadline')+'</b></div><div class="meter"><span>Duration</span><b>'+(e.duration_minutes?esc(e.duration_minutes)+' min':'No limit')+'</b></div><button class="btn primary" onclick="startExam('+e.id+')">Open exam →</button></article>').join('')||'<div class="card empty">No exams have been published yet.</div>')+'</div>'}
async function startExam(id){try{const d=await api('/api/exams/'+id+'/start',{method:'POST'});window.__examRun=d;const q=d.questions||[];modal('<div class="modalhead"><h2>'+esc(d.exam.title)+'</h2><span id="examTimer" class="badge red">--:--</span><button class="close" onclick="window.close()">×</button></div><div id="examForm">'+q.map((x,i)=>'<div class="card" style="margin:10px 0"><b>'+(i+1)+'. '+esc(x.question_text)+'</b>'+(x.question_type==='MCQ'?'<div class="list" style="margin-top:10px">'+(x.options_json||[]).map(o=>'<label class="item"><input type="radio" name="q_'+x.id+'" value="'+esc(o)+'"> <span>'+esc(o)+'</span></label>').join('')+'</div>':x.question_type==='TRUE_FALSE'?'<div class="list" style="margin-top:10px"><label class="item"><input type="radio" name="q_'+x.id+'" value="True"> True</label><label class="item"><input type="radio" name="q_'+x.id+'" value="False"> False</label></div>':'<textarea id="short_'+x.id+'" rows="3" style="margin-top:10px" placeholder="Your answer..."></textarea>')+'</div>').join('')+'</div><button class="btn primary" onclick="submitExam()">Submit exam</button>');startExamTimer(new Date(d.attempt.deadline).getTime())}catch(x){toast(x.message)}}
let examTimerHandle=null;function startExamTimer(deadline){clearInterval(examTimerHandle);const tick=()=>{const ms=Math.max(0,deadline-Date.now());const sec=Math.floor(ms/1000);const el=$('#examTimer');if(el)el.textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');if(ms<=0){clearInterval(examTimerHandle);submitExam(true)}};tick();examTimerHandle=setInterval(tick,1000)}
async function submitExam(auto=false){if(!window.__examRun)return;const answers={};for(const q of window.__examRun.questions||[]){if(q.question_type==='SHORT')answers[q.id]=$('#short_'+q.id)?.value||'';else answers[q.id]=document.querySelector('input[name="q_'+q.id+'"]:checked')?.value||''}try{const d=await api('/api/exams/'+window.__examRun.exam.id+'/submit',{method:'POST',body:JSON.stringify({answers})});clearInterval(examTimerHandle);window.close();toast((auto?'Time ended. ':'')+'Exam submitted. Score: '+d.score);await loadData();render()}catch(x){toast(x.message);if(auto){window.close()}}}
function aiModal(){modal('<div class="modalhead"><h2>✦ '+t('ai')+'</h2><button class="close" onclick="window.close()">×</button></div><p class="muted">'+(S.lang==='ar'?'مساعد B4 يعمل من الـBackend باستخدام Gemini. المفتاح لا يظهر للطلاب.':'B4 AI runs through the backend using Gemini. The key never reaches students.')+'</p><div class="field"><label>Question</label><textarea id="aiq" rows="5" placeholder="'+(S.lang==='ar'?'مثلاً: اشرح TDM بطريقة بسيطة':'Example: Explain TDM simply')+'"></textarea></div><button class="btn primary" onclick="answerAI()">Ask AI →</button><div id="air" style="margin-top:14px"></div>')}
