-- B4 Class production schema
-- MySQL 8.x / Railway. No CREATE DATABASE or USE.

CREATE TABLE IF NOT EXISTS students(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_code VARCHAR(40) NOT NULL UNIQUE,
 official_name VARCHAR(255) NOT NULL,
 display_name VARCHAR(120) NOT NULL,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 specialization VARCHAR(120) NOT NULL DEFAULT 'Telecommunication',
 avatar_url VARCHAR(500),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS teachers(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 teacher_code VARCHAR(40) UNIQUE,
 official_name VARCHAR(255) NOT NULL,
 display_name VARCHAR(120) NOT NULL,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 avatar_url VARCHAR(500),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_id INT UNSIGNED NULL,
 teacher_id INT UNSIGNED NULL,
 official_name VARCHAR(255) NOT NULL,
 display_name VARCHAR(120) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('STUDENT','TEACHER') NOT NULL DEFAULT 'STUDENT',
 is_super_admin TINYINT(1) NOT NULL DEFAULT 0,
 status ENUM('ACTIVE','SUSPENDED','DISABLED') NOT NULL DEFAULT 'ACTIVE',
 avatar_url VARCHAR(500),
 session_version INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE SET NULL,
 FOREIGN KEY(teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
 INDEX(role),INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS permissions(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(80) NOT NULL UNIQUE,
 label VARCHAR(160) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS role_permissions(
 role ENUM('STUDENT','TEACHER') NOT NULL,
 permission_id INT UNSIGNED NOT NULL,
 PRIMARY KEY(role,permission_id),
 FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_permissions(
 user_id BIGINT UNSIGNED NOT NULL,
 permission_id INT UNSIGNED NOT NULL,
 granted_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,permission_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
 FOREIGN KEY(granted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activation_keys(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 key_hash CHAR(64) NOT NULL UNIQUE,
 key_preview VARCHAR(30) NOT NULL,
 key_value VARCHAR(80) NULL,
 person_type ENUM('STUDENT','TEACHER') NOT NULL,
 student_id INT UNSIGNED NULL,
 teacher_id INT UNSIGNED NULL,
 official_name VARCHAR(255) NOT NULL,
 status ENUM('ACTIVE','USED','REVOKED','EXPIRED') NOT NULL DEFAULT 'ACTIVE',
 created_by BIGINT UNSIGNED NULL,
 used_user_id BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 expires_at DATETIME NULL,
 used_at DATETIME NULL,
 FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE SET NULL,
 FOREIGN KEY(teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(used_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subjects(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 teacher_name VARCHAR(160),
 progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_subject_class(name,class_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 day_order TINYINT UNSIGNED NOT NULL,
 day_name VARCHAR(30) NOT NULL,
 p1 VARCHAR(160),p2 VARCHAR(160),p3 VARCHAR(160),p4 VARCHAR(160),
 UNIQUE KEY uq_schedule_day(class_name,day_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assignments(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(200) NOT NULL,description TEXT,
 status ENUM('OPEN','DONE','CLOSED') NOT NULL DEFAULT 'OPEN',
 subject_id INT UNSIGNED NULL,class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 due_at DATETIME NULL,created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assignment_submissions(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 assignment_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,
 content TEXT,file_url VARCHAR(500),
 status ENUM('SUBMITTED','GRADED') NOT NULL DEFAULT 'SUBMITTED',
 score DECIMAL(6,2) NULL,submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 UNIQUE KEY uq_submission(assignment_id,user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resources(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(220) NOT NULL,description TEXT,
 resource_type ENUM('LINK','FILE','VIDEO','NOTE') NOT NULL DEFAULT 'LINK',
 url VARCHAR(1000),file_url VARCHAR(500),subject_id INT UNSIGNED NULL,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resource_files(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 resource_id BIGINT UNSIGNED NOT NULL,
 filename VARCHAR(255) NOT NULL,mime_type VARCHAR(120) NOT NULL,data LONGBLOB NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exams(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(220) NOT NULL,description TEXT,subject_id INT UNSIGNED NULL,
 class_name VARCHAR(20) NOT NULL DEFAULT 'B4',starts_at DATETIME NULL,ends_at DATETIME NULL,
 duration_minutes SMALLINT UNSIGNED NULL,
 status ENUM('DRAFT','SCHEDULED','OPEN','CLOSED') NOT NULL DEFAULT 'DRAFT',
 created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_questions(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,exam_id BIGINT UNSIGNED NOT NULL,
 question_text TEXT NOT NULL,question_type ENUM('MCQ','TRUE_FALSE','SHORT') NOT NULL DEFAULT 'MCQ',
 options_json JSON NULL,correct_answer TEXT NULL,points DECIMAL(6,2) NOT NULL DEFAULT 1,
 sort_order INT UNSIGNED NOT NULL DEFAULT 0,
 FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_attempts(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,exam_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,
 status ENUM('STARTED','SUBMITTED','REVIEWED') NOT NULL DEFAULT 'STARTED',
 score DECIMAL(8,2) NULL,started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,submitted_at DATETIME NULL,
 UNIQUE KEY uq_exam_attempt(exam_id,user_id),
 FOREIGN KEY(exam_id) REFERENCES exams(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_answers(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,attempt_id BIGINT UNSIGNED NOT NULL,
 question_id BIGINT UNSIGNED NOT NULL,answer_text TEXT,is_correct BOOLEAN NULL,
 points_awarded DECIMAL(8,2) NULL,
 FOREIGN KEY(attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
 FOREIGN KEY(question_id) REFERENCES exam_questions(id) ON DELETE CASCADE,
 UNIQUE KEY uq_attempt_question(attempt_id,question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS announcements(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(220) NOT NULL,body TEXT NOT NULL,
 category VARCHAR(60) NOT NULL DEFAULT 'General',class_name VARCHAR(20) NOT NULL DEFAULT 'B4',
 created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_messages(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,body TEXT NOT NULL,
 reply_to_id BIGINT UNSIGNED NULL,file_url VARCHAR(500),deleted_at DATETIME NULL,deleted_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,edited_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(reply_to_id) REFERENCES chat_messages(id) ON DELETE SET NULL,
 FOREIGN KEY(deleted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_message_edits(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,message_id BIGINT UNSIGNED NOT NULL,
 editor_user_id BIGINT UNSIGNED NULL,old_body TEXT NOT NULL,new_body TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
 FOREIGN KEY(editor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS linked_accounts(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,
 provider ENUM('GOOGLE','DISCORD','FACEBOOK') NOT NULL,provider_user_id VARCHAR(255) NOT NULL,
 provider_email VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_provider(provider,provider_user_id),UNIQUE KEY uq_user_provider(user_id,provider),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,title VARCHAR(220) NOT NULL,
 body TEXT,read_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS security_logs(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,actor_user_id BIGINT UNSIGNED NULL,action VARCHAR(100) NOT NULL,
 details TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_logs(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,actor_user_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,
 entity_type VARCHAR(80),entity_id BIGINT UNSIGNED,details TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_conversations(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(200),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_messages(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,conversation_id BIGINT UNSIGNED NOT NULL,
 role ENUM('USER','ASSISTANT') NOT NULL,content TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_attendance(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,
 attendance_date DATE NOT NULL,status ENUM('PRESENT','ABSENT') NOT NULL DEFAULT 'PRESENT',
 marked_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_b4_attendance(user_id,attendance_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_badges(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,
 description VARCHAR(500),icon_mime VARCHAR(120),icon_data MEDIUMBLOB,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_user_badges(
 user_id BIGINT UNSIGNED NOT NULL,badge_id BIGINT UNSIGNED NOT NULL,assigned_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,badge_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_developers(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,link_url VARCHAR(500) NULL,
 image_mime VARCHAR(120),image_data MEDIUMBLOB,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_teacher_messages(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,body TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b4_teacher_typing(
 user_id BIGINT UNSIGNED PRIMARY KEY,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profile_images(
 entity_type VARCHAR(20) NOT NULL,entity_id BIGINT UNSIGNED NOT NULL,mime_type VARCHAR(120) NOT NULL,
 data MEDIUMBLOB NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(entity_type,entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_typing(
 user_id BIGINT UNSIGNED PRIMARY KEY,typing TINYINT(1) NOT NULL DEFAULT 0,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO permissions(code,label) VALUES
('MANAGE_ADMINS','Manage admins'),('MANAGE_ACCOUNTS','Manage accounts'),('MANAGE_KEYS','Manage activation keys'),
('MANAGE_TEACHERS','Manage teachers'),('MANAGE_STUDENTS','Manage students'),('MANAGE_ROLES','Manage roles'),('MANAGE_PERMISSIONS','Manage permissions'),('VIEW_ADMIN_CENTER','View Admin Center'),
('MANAGE_SUBJECTS','Manage subjects'),('MANAGE_SCHEDULE','Manage schedule'),('MANAGE_ASSIGNMENTS','Manage assignments'),
('MANAGE_RESOURCES','Manage resources'),('MANAGE_EXAMS','Manage exams'),('MANAGE_ATTENDANCE','Manage attendance'),
('MANAGE_ANNOUNCEMENTS','Manage announcements'),('MANAGE_CHAT','Moderate chat'),('VIEW_LOGS','View logs'),
('USE_AI','Use B4 AI'),('VIEW_CLASS','View class'),('MANAGE_BADGES','Manage badges'),
('MANAGE_DEVELOPERS','Manage developers'),('MANAGE_TEACHER_CHAT','Teacher chat'),
('MANAGE_ANALYTICS','View attendance analytics'),('ADMINISTRATOR','Administrator');

INSERT IGNORE INTO role_permissions(role,permission_id) SELECT 'SUPER_ADMIN',id FROM permissions;
INSERT IGNORE INTO role_permissions(role,permission_id) SELECT 'TEACHER',id FROM permissions WHERE code IN
('MANAGE_SUBJECTS','MANAGE_ASSIGNMENTS','MANAGE_RESOURCES','MANAGE_EXAMS','MANAGE_ATTENDANCE','MANAGE_ANNOUNCEMENTS','MANAGE_CHAT','USE_AI','VIEW_CLASS','MANAGE_TEACHER_CHAT');
INSERT IGNORE INTO role_permissions(role,permission_id) SELECT 'ADMIN',id FROM permissions WHERE code IN
('MANAGE_ACCOUNTS','MANAGE_STUDENTS','MANAGE_TEACHERS','MANAGE_KEYS','MANAGE_SUBJECTS','MANAGE_SCHEDULE','MANAGE_ASSIGNMENTS','MANAGE_RESOURCES','MANAGE_EXAMS','MANAGE_ATTENDANCE','MANAGE_ANNOUNCEMENTS','MANAGE_CHAT','VIEW_LOGS','USE_AI','VIEW_CLASS','MANAGE_BADGES','MANAGE_DEVELOPERS','MANAGE_ANALYTICS','ADMINISTRATOR');
INSERT IGNORE INTO role_permissions(role,permission_id) SELECT 'STUDENT',id FROM permissions WHERE code IN('USE_AI','VIEW_CLASS');